/* Dansk indhold + UI-tekster.
   Intervallerne følger Volvo Penta D4/D6-instruktionsbogen
   (olie/filter 200 t eller 12 mdr., impeller årligt, kølervæske hvert 4. år osv.)
   VIGTIGT: id'erne skal matche content-en.js — gemte data er nøglet på dem. */

CONTENT.da = {
  groups: [
    { id: "engine",    name: "Motor",            icon: "⚙️" },
    { id: "underwater",name: "Under vandlinjen", icon: "🌊" },
    { id: "systems",   name: "Bådens systemer",  icon: "🔌" },
    { id: "safety",    name: "Sikkerhedsudstyr", icon: "🦺" },
  ],

  services: [
    // MOTOR — Volvo Penta D4/D6
    { id: "oil",        group: "engine", name: "Motorolie & filter",
      intervalHours: 200, intervalMonths: 12,
      why: "Frisk olie er den billigste motorforsikring, der findes. Gammel olie bliver sur og slider motoren indefra. Skift mens motoren er varm, så den gamle olie løber helt ud." },
    { id: "fuelfilter", group: "engine", name: "Brændstoffiltre (motor + vandudskiller)",
      intervalHours: 400, intervalMonths: 12,
      why: "Diesel trækker vand og kan gro bakterier ('dieselpest'). Filtrene og vandudskillerens skål er det eneste værn mellem det og dine dyser. Tap skålen af, så snart du ser vand i den." },
    { id: "impeller",   group: "engine", name: "Impeller (søvandspumpe)",
      intervalMonths: 12,
      why: "Et lille gummiskovlhjul, der pumper søvand gennem motorens kølesystem. Når den svigter, koger motoren over på få minutter. Billig del, store konsekvenser — skift hver sæson og hav altid en i reserve om bord." },
    { id: "belts",      group: "engine", name: "Kileremme — tjek & spænding",
      intervalMonths: 12,
      why: "Remmene trækker generatoren og cirkulationspumpen. Se efter revner, blanke flader og sort gummistøv under remmen (et slidtegn). Tryk midt mellem remskiverne: ca. 1 cm eftergivenhed er passende." },
    { id: "airfilter",  group: "engine", name: "Luftfilter",
      intervalHours: 400, intervalMonths: 24,
      why: "Et tilstoppet filter får motoren til at ryge og miste kraft. Hurtigt visuelt tjek årligt, skift når det er snavset." },
    { id: "coolant",    group: "engine", name: "Kølervæske (VCS) — udskiftning",
      intervalMonths: 48, pro: true,
      why: "Kølervæsken i det lukkede kredsløb (Volvos gule VCS) mister sin korrosionsbeskyttelse med tiden. Tjek niveauet før hver tur; skift væsken hvert 4. år." },
    { id: "valves",     group: "engine", name: "Ventilspillerum — kontrol",
      intervalHours: 1000, intervalMonths: 60, pro: true,
      why: "Et værkstedsjob på Volvos skema. Værd at bestille sammen med et stort serviceeftersyn." },
    { id: "heatex",     group: "engine", name: "Varmeveksler & ladeluftkøler — service",
      intervalHours: 1000, intervalMonths: 48, pro: true,
      why: "Søvandet kalker langsomt kølekernerne til. Et værksted renser og tryktester dem. At springe det over er en klassisk årsag til snigende overophedning på ældre D-motorer." },
    { id: "enginezinc", group: "engine", name: "Motorzink (kølesystem)",
      intervalMonths: 12,
      why: "Små zinkstifter skruet ind i varmeveksleren — motorens egne offeranoder, der beskytter kølekredsløbet mod tæring. Skru dem ud og tjek: mere end halvt tæret = skift. Volvo-værkstedet sætter nye i ved de store serviceeftersyn." },

    // UNDER VANDLINJEN
    { id: "anodes",     group: "underwater", name: "Offeranoder",
      intervalMonths: 12,
      why: "Klumper af zink/aluminium på aksel, ror, trimflaps og bovpropel, der tærer, så dine metaldele ikke gør det. Skift dem, der er mere end halvt væk — de er billig forsikring. Mal aldrig hen over dem." },
    { id: "antifoul",   group: "underwater", name: "Bundmaling",
      intervalMonths: 12,
      why: "Holder rurer og alger væk fra bunden. En begroet bund kan koste flere knob og en masse diesel. Mal (eller som minimum pletreparér) hvert forår før søsætning." },
    { id: "propshaft",  group: "underwater", name: "Propel & aksel — eftersyn",
      intervalMonths: 12,
      why: "Tjek propellen for hakker (de giver vibrationer), og se efter fiskeline viklet om akslen ved tætningen — den ødelægger pakdåser. Tag fat i akslen og mærk efter slør i lejet." },
    { id: "shaftseal",  group: "underwater", name: "Akseltætning / pakdåse",
      intervalHours: 500, intervalMonths: 60, pro: true,
      why: "Dér hvor skrueakslen går ud gennem skroget. Volvos gummitætning skal 'bøvses' (klemmes så luften slipper ud) ved hver søsætning og skiftes ca. hvert 5. år. Den skal være tør — vand her løber direkte ned i bunden af båden." },
    { id: "seacocks",   group: "underwater", name: "Søventiler — motionér & smør",
      intervalMonths: 12,
      why: "Hver ventil sidder på et hul i skroget. Åbn og luk dem alle helt et par gange, så de aldrig sætter sig fast — en søventil, du ikke kan lukke i en nødsituation, er en synkerisiko. Smør ved optagning." },
    { id: "hoses",      group: "underwater", name: "Slanger & spændbånd under vandlinjen",
      intervalMonths: 12,
      why: "Klem på slangerne (bløde eller revnede = skift) og tjek, at alle spændbånd er stramme og uden rust. Kritiske slanger under vandlinjen bør have dobbelte spændbånd." },
    { id: "thruster",   group: "underwater", name: "Bovpropel — anode, propel & olie",
      intervalMonths: 12,
      why: "Bovpropellens drev har sin egen lille anode, der forsvinder hurtigt. Tjek at propellen drejer frit uden tang og liner, og tjek gearolien hvis din model tillader det." },
    { id: "rudder",     group: "underwater", name: "Ror & styring — kontrol",
      intervalMonths: 12,
      why: "Ved optagning: skub til roret med hånden — mærkbart slør betyder slidte lejer. Drej rattet fra yderstilling til yderstilling og tjek hydraulikolien ved rorpumpen." },

    // BÅDENS SYSTEMER
    { id: "batteries",  group: "systems", name: "Batterier — poler & tilstand",
      intervalMonths: 12,
      why: "Rens og fedt polerne, tjek at batterierne er spændt fast, og mål en hvilespænding på ~12,6 V+. De fleste Marex-både har separat startbatteri og forbrugsbank — tjek begge." },
    { id: "freshwater", group: "systems", name: "Ferskvandssystem — skyl & desinficér",
      intervalMonths: 12,
      why: "Efter vinteren: skyl frostvæsken ud og desinficér tanken (fx med klorinopløsning), og skyl efter. Tjek også at pumpen ikke starter af sig selv, når ingen hane er åben — det betyder en utæthed." },
    { id: "toilet",     group: "systems", name: "Toilet & holdingtank — service",
      intervalMonths: 12,
      why: "Smør pumpe/ventiler, tjek jokerventilen, skyl holdingtanken. Pas godt på slangerne — gamle toiletslanger er den klassiske kilde til lugt." },
    { id: "heater",     group: "systems", name: "Dieselvarmer (Webasto/Eberspächer) — service",
      intervalMonths: 12, pro: true,
      why: "Almindelig i Marex-både. Kør den for fuld kraft 20+ minutter hver måned, også om sommeren, så den ikke soder til; få den serviceret når den begynder at ryge eller lugte." },
    { id: "gas",        group: "systems", name: "Gasanlæg — tæthedsprøve",
      intervalMonths: 12, pro: true,
      why: "Har du gaskomfur: Slangerne har påtrykt udløbsdato, og anlægget bør tæthedsprøves (et professionelt tjek hvert andet år er givet godt ud). Gas synker ned i bunden af båden — tag det alvorligt." },
    { id: "windlass",   group: "systems", name: "Ankerspil & kæde",
      intervalMonths: 12,
      why: "Smør ankerspillet, kør kæden ud og efterse den, og frisk længdemarkeringerne op. Tjek at sjæklen mellem kæde og anker er sikret med tråd." },
    { id: "trimtabs",   group: "systems", name: "Trimflaps — kontrol",
      intervalMonths: 12,
      why: "Kør dem helt op og ned og se, at de bevæger sig. Tjek hydraulikslanger, hængselsbolte og de små anoder på selve flapsene." },
    { id: "canvas",     group: "systems", name: "Kaleche, luger & gummilister — smøring",
      intervalMonths: 12,
      why: "Silikonefedt på gummilisterne ved luger og skydetag, smør lynlåse, og tjek at afløbene i cockpittet ikke er stoppede." },

    // SIKKERHED
    { id: "extinguisher", group: "safety", name: "Brandslukkere — kontrol",
      intervalMonths: 12,
      why: "Manometer i det grønne, plombe intakt, ingen rust. Vend pulverslukkere på hovedet og ryst dem, så pulveret ikke klumper. Professionelt eftersyn efter mærkaten." },
    { id: "lifejackets", group: "safety", name: "Redningsveste — eftersyn & service",
      intervalMonths: 12,
      why: "For oppustelige veste: tjek at gaspatronen er skruet fast og ikke er rusten, og at den automatiske udløser er inden for datoen. De fleste producenter kræver fuldt eftersyn hvert 1.–2. år." },
    { id: "flares",     group: "safety", name: "Nødraketter & nødblus — udløbsdato",
      intervalMonths: 12,
      why: "Nødsignaler udløber efter 3–4 år. Tjek datoerne hvert forår og udskift de udløbne (aflevér dem — smid dem ikke i skraldespanden)." },
    { id: "firstaid",   group: "safety", name: "Førstehjælpskasse — opfyldning",
      intervalMonths: 12,
      why: "Tjek udløbsdato på det hele, og fyld op med plastre og søsygetabletter før sæsonen." },
    { id: "alarms",     group: "safety", name: "Røg-/gas-/CO-alarmer",
      intervalMonths: 12,
      why: "Test alarmerne med testknappen og skift batterier hvert forår. Dieselvarmer plus lukket båd gør en CO-alarm til billig livsforsikring." },
  ],

  checklists: [
    {
      id: "launch", name: "Forår — i vandet", icon: "🌱",
      desc: "Søsætning & klargøring. Arbejd oppefra og ned: alt på land først, derefter tjek i vandet i samme øjeblik hun flyder.",
      sections: [
        { name: "På land, før søsætning", items: [
          { id: "af",      text: "Bundmaling malet / pletrepareret", sub: "Bunden ren, slebet hvor malingen skaller, nyt lag på. Mal ikke anoderne!" },
          { id: "anodes",  text: "Anoder tjekket — skiftet hvis >50 % tæret", sub: "Aksel, ror, trimflaps, bovpropel." },
          { id: "hull",    text: "Skrog, propel, aksel & ror efterset", sub: "Hakker i propellen, slør i aksel/ror, skader eller blærer i gelcoaten." },
          { id: "seacock", text: "Alle søventiler motioneret & smurt", sub: "Åbn og luk hver enkelt helt et par gange. De skal gå let." },
          { id: "hoses",   text: "Slanger & spændbånd under vandlinjen tjekket", sub: "Klemmetest, spændbånd efterspændt, dobbelte bånd på kritiske slanger." },
          { id: "impeller",text: "Impeller monteret & søvandssystem samlet", sub: "Hvis du tog den ud til vinteren. Lidt opvaskemiddel på vingerne hjælper på tørstarten." },
          { id: "engine",  text: "Motor: oliestand, kølervæske, remme", sub: "Olie mellem mærkerne, kølervæske mellem MIN/MAX (kold), remme faste og uden revner." },
          { id: "batt",    text: "Batterier tilsluttet & fuldt opladet", sub: "Poler spændt og fedtet ind. Tjek hvilespænding ~12,6 V+." },
          { id: "plugs",   text: "BUNDPROPPER I", sub: "Klassikeren. Tjek at alle bundpropper er monteret, før hun rammer vandet." },
        ]},
        { name: "I vandet — de første 10 minutter", items: [
          { id: "leaks",   text: "Lækagetjek ved akseltætning, søventiler & gennemføringer", sub: "Gå straks ned og kig. En tør bund skal forblive tør." },
          { id: "burp",    text: "Akseltætning 'bøvset' (Volvo-gummitætning)", sub: "Klem på gummibælgen til der sprøjter vand ud — det lukker indespærret luft ud, så den smører sig selv." },
          { id: "start",   text: "Motor startet — søvand ud af udstødningen inden for sekunder", sub: "Intet vand = stop med det samme. Tjek at søventilen er åben og filteret er fyldt." },
          { id: "gauges",  text: "Olietryk, temperatur & ladning normal", sub: "Hold øje med instrumenterne de første minutter ved kajen." },
          { id: "steer",   text: "Styring fra ende til anden, gas & gear testet", sub: "Kort frem/bak mod fortøjningerne." },
          { id: "thruster",text: "Bovpropel & trimflaps testet", sub: "" },
        ]},
        { name: "Klargøring af båden", items: [
          { id: "water",   text: "Ferskvandssystem skyllet & fyldt", sub: "Skyl al frostvæske ud af alle haner (varmt + koldt), før der fyldes til brug." },
          { id: "elec",    text: "Lanterner, horn, vinduesviskere, VHF testet", sub: "" },
          { id: "bilge",   text: "Lænsepumpe testet — auto-svømmer & manuel", sub: "Løft svømmerafbryderen med hånden og lyt efter pumpen." },
          { id: "safety",  text: "Sikkerhedsudstyr om bord & inden for dato", sub: "Redningsveste, brandslukkere, nødsignaler, førstehjælpskasse." },
          { id: "lines",   text: "Fortøjninger, fendere & anker klargjort", sub: "" },
          { id: "hours",   text: "Motortimer noteret som sæsonstart", sub: "Opdatér timerne under Hjem." },
        ]},
      ],
    },
    {
      id: "haulout", name: "Efterår — op af vandet", icon: "❄️",
      desc: "Optagning & vinterklargøring. Den gyldne regel: intet vand dér hvor det kan fryse, ingen halvtom dieseltank, ingen flade batterier.",
      sections: [
        { name: "I vandet, før optagning", items: [
          { id: "fuel",    text: "Dieseltank fyldt + additiv tilsat", sub: "En fuld tank kan ikke danne kondensvand på væggene. Tilsæt middel mod dieselpest." },
          { id: "oil",     text: "Motorolie & filter skiftet (varm motor)", sub: "Gammel sur olie skal ikke stå i motoren hele vinteren. Kør hende varm først." },
          { id: "holding", text: "Holdingtank tømt & skyllet", sub: "" },
        ]},
        { name: "Ved optagningen", items: [
          { id: "wash",    text: "Bunden højtryksspulet med det samme", sub: "Begroningen går 10× lettere af, mens den stadig er våd." },
          { id: "inspect", text: "Skrog, propel, aksel, ror & anoder efterset", sub: "Fotografér alt mistænkeligt nu — det er glemt til foråret. Notér anodernes tilstand." },
        ]},
        { name: "På land — motor & systemer", items: [
          { id: "raw",     text: "Søvandssystem vinterklargjort", sub: "Luk søventilen, åbn filteret, kør motoren på frostvæske hældt i filteret, til det løber farvet ud af udstødningen." },
          { id: "imp",     text: "Impeller taget ud (eller noteret som siddende i)", sub: "Opbevaret fladt holder den formen. Skriv ned hvad du gjorde, så forårs-dig ved det." },
          { id: "fresh",   text: "Ferskvandssystem tømt + frostvæske", sub: "Tank, pumpe, vandvarmer, alle haner (varmt & koldt), agterbruser. Kun giftfri propylenglykol." },
          { id: "toilet",  text: "Toilet & holdingtank vinterklargjort", sub: "Pump frostvæske gennem toilettet og lad lidt stå i kumme & tank." },
          { id: "batt",    text: "Batterier fuldt opladet + frakoblet eller på vedligeholdelseslader", sub: "Et opladet batteri fryser ikke; et fladt kan revne ved -10 °C." },
          { id: "coolant", text: "Kølervæskens frostsikring målt", sub: "Det lukkede kredsløb skal beskytte til mindst -25 °C." },
        ]},
        { name: "På land — båden", items: [
          { id: "remove",  text: "Elektronik, redningsveste, hynder, mad & væsker fjernet", sub: "Alt der kan fryse, mugne eller blive stjålet, skal med hjem." },
          { id: "fridge",  text: "Køleskab afrimet & sat på klem", sub: "" },
          { id: "vent",    text: "Båden udluftet + fugtfjernere sat op", sub: "Åbn skabe og dørkluger, så luften kan cirkulere." },
          { id: "grease",  text: "Søventiler smurt, stillet som pladsen anbefaler", sub: "" },
          { id: "cover",   text: "Presenning monteret & tjekket for gnav", sub: "Tjek den igen efter den første storm." },
          { id: "hours",   text: "Motortimer noteret som sæsonafslutning", sub: "Opdatér timerne under Hjem." },
        ]},
      ],
    },
    {
      id: "pretrip", name: "Før hver tur", icon: "🧭",
      desc: "5-minutters tjekket før du kaster los. Nulstiller sig selv automatisk, så den altid er klar.",
      autoReset: true,
      sections: [
        { name: "Motorrum (åbn lugen!)", items: [
          { id: "oil",    text: "Oliestand mellem mærkerne", sub: "" },
          { id: "coolant",text: "Kølervæske mellem MIN/MAX", sub: "Tjek kun kold." },
          { id: "look",   text: "Kig & lugt: ingen diesel, olie eller vand hvor det ikke hører til", sub: "30 sekunder med øjne og næse finder de fleste problemer i tide." },
          { id: "strainer",text:"Søvandsfilter rent", sub: "Et blik gennem den klare skål — ingen tang eller plastposer." },
        ]},
        { name: "Båden", items: [
          { id: "bilge",  text: "Bunden tør, lænsepumpe på auto", sub: "" },
          { id: "fuel",   text: "Diesel nok: ⅓ ud, ⅓ hjem, ⅓ reserve", sub: "" },
          { id: "batt",   text: "Hovedafbrydere til, spænding OK", sub: "" },
          { id: "weather",text: "Vejr- & vindudsigt tjekket", sub: "" },
          { id: "plan",   text: "Fortalt nogen hvor du sejler hen", sub: "" },
          { id: "jackets",text: "Redningsveste fremme — én til alle om bord", sub: "" },
        ]},
        { name: "Efter motorstart", items: [
          { id: "water",  text: "Søvand løber ud af udstødningen", sub: "Kig over siden inden for sekunder efter start." },
          { id: "gauges", text: "Olietryk & ladning normal", sub: "" },
          { id: "lines",  text: "Fendere ind, ingen liner der hænger i vandet", sub: "En line i propellen slutter turen." },
        ]},
      ],
    },
    {
      id: "posttrip", name: "Efter hver tur", icon: "🏁",
      desc: "Forlad båden, så næste tur starter let. Nulstiller automatisk.",
      autoReset: true,
      sections: [
        { name: "Båden sikres", items: [
          { id: "hours",  text: "Motortimer opdateret i appen", sub: "Hjem → opdatér timer. Det driver alle servicepåmindelserne." },
          { id: "lines",  text: "Fortøjninger & fendere sat efter kommende vejr", sub: "" },
          { id: "bilge",  text: "Bunden tjekket tør", sub: "" },
          { id: "seacocks",text:"Søventiler til toilet & pantry lukket, hvis båden forlades", sub: "" },
          { id: "shore",  text: "Landstrøm tilsluttet, lader tændt", sub: "" },
          { id: "fridge", text: "Letfordærveligt ud af køleskabet (hvis væk >2 dage)", sub: "" },
          { id: "rinse",  text: "Hurtig ferskvandsskylning af cockpit & rustfrit stål", sub: "Det er saltet, der ælder båden." },
          { id: "canvas", text: "Kaleche/presenninger på, luger lukket, båden låst", sub: "" },
        ]},
      ],
    },
    {
      id: "monthly", name: "Månedligt i sæsonen", icon: "📅",
      desc: "En 30-minutters runde en gang om måneden holder overraskelserne væk. Nulstiller automatisk når du gennemfører den.",
      autoReset: true,
      sections: [
        { name: "Den månedlige runde", items: [
          { id: "strainer",text:"Søvandsfilter åbnet & renset", sub: "Luk søventilen først, rens kurven, åbn igen — og tjek at der løber vand, når motoren starter." },
          { id: "belts",  text: "Blik på remmene: spænding OK, intet sort støv", sub: "" },
          { id: "clamps", text: "Spændbånd i motorrummet efterset", sub: "" },
          { id: "batt",   text: "Batteripoler & laderens tilstand tjekket", sub: "" },
          { id: "bilgep", text: "Lænsepumpens svømmerafbryder testet med hånden", sub: "" },
          { id: "anode",  text: "Synlige anoder tjekket (trimflaps / bovpropel hvis muligt)", sub: "" },
          { id: "chafe",  text: "Fortøjninger tjekket for gnav", sub: "" },
          { id: "ext",    text: "Brandslukkernes manometre i det grønne", sub: "" },
          { id: "heater", text: "Dieselvarmer kørt 20 min for fuld kraft", sub: "Holder den fri for sod." },
          { id: "wash",   text: "Båden vasket, afløb & spygatter fri", sub: "" },
        ]},
      ],
    },
  ],

  guide: [
    { id: "impeller", name: "Impeller (søvandspumpe)", icon: "🌀",
      what: "Et stjerneformet gummihjul inde i en bronzepumpe foran/på siden af motoren. Den suger søvand ind gennem skroget og presser det gennem varmeveksleren for at køle motoren.",
      where: "På Volvo Penta D-serien sidder den bag et rundt dæksel med 4–6 skruer på søvandspumpen, lavt foran på motoren. Følg slangen fra søvandsfilteret — den ender ved pumpen.",
      look: "Gummivingerne skal være bløde og hele. Revnede, stive eller manglende vinger = skift nu (og find de manglende stykker i varmeveksleren, før de blokerer den).",
      when: "Skift hver 12. måned. Hav altid et ekstra impellersæt om bord." },
    { id: "strainer", name: "Søvandsfilter", icon: "🧺",
      what: "Et filter med en klar skål, der fanger tang, plastik og brandmænd, før de når motorens kølevandspumpe.",
      where: "Mellem motorens søventil og motoren, i motorrummet — typisk monteret på et skot nær motoren, med gennemsigtigt låg eller skål.",
      look: "Du skal kunne se igennem det. Tang, mudder eller en sammenfalden kurv betyder rensetid. Luk søventilen, før du åbner det!",
      when: "Et blik før hver tur, rens månedligt i sæsonen." },
    { id: "anodes", name: "Offeranoder", icon: "🧲",
      what: "Klodser af zink (saltvand) eller aluminium, der med vilje tærer væk og beskytter propel, aksel, ror og trimflaps mod galvanisk tæring.",
      where: "På akslen (en krave), på roret, på hver trimflap og en lille ring eller skive på bovpropellens drev. Der kan også sidde en pæreformet skroganode.",
      look: "En sund anode er ru og mat af at tære. Skinnende, urørte anoder har måske ikke god kontakt. Mere end ~50 % tæret = skift.",
      when: "Tjek ved hver optagning, skift årligt eller ved 50 % tæring. Mal dem aldrig." },
    { id: "antifoul", name: "Bundmaling", icon: "🎨",
      what: "Biocidmaling på bunden, der forhindrer rurer og alger i at gro. En begroet bund stjæler fart og brænder ekstra diesel af.",
      where: "Alt under vandlinjen. Propel og aksel kan få deres egen særlige propelcoating.",
      look: "Ved optagning: hvis bunden var slimet/grøn men spules ren, virker malingen. Fastsiddende rurer = tid til nyt lag (eller en bedre maling).",
      when: "Mal hvert forår før søsætning. Tjek de lokale regler — nogle havne i Østersøen begrænser malingstyper." },
    { id: "seacocks", name: "Søventiler & gennemføringer", icon: "🔩",
      what: "Kuglehaner på hvert hul i skroget: motorens køleindtag, toilet ind/ud, vaskeafløb osv. Bådens nødafbrydere.",
      where: "Følg en hvilken som helst slange nedad, og den ender ved en søventil nær skroget. Typiske steder: motorrum (motorindtag), under toiletvasken (toilet), under vasken i pantryet.",
      look: "Håndtaget skal kunne drejes en kvart omgang med fast håndkraft. Stramt = smør den. Sidder fast = få den serviceret — en søventil, du ikke kan lukke, er farlig. Se efter grøn ir på bronze.",
      when: "Motionér dem alle et par gange hver sæson; smør ved optagning. Kend hver eneste af dem — tæl dem." },
    { id: "shaftseal", name: "Akseltætning (pakdåse)", icon: "💧",
      what: "Tætningen dér, hvor den roterende skrueaksel går ud gennem skroget. På de fleste Volvo-anlæg er det en sort gummitætning, der kører tørt.",
      where: "I bunden helt agter ved motoren/gearkassen — følg akslen agterud fra gearkassen, til den forsvinder gennem skroget.",
      look: "Den skal være tør. Drypper den under sejlads eller i ro = den skal efterses. Efter hver søsætning: klem ('bøvs') gummibælgen, til der sprøjter vand ud, så den er vandsmurt og ikke har luft i.",
      when: "Bøvs ved hver søsætning. Skift ca. hvert 5. år / 500 t (værkstedsjob — koblingen skal trækkes)." },
    { id: "oilcheck", name: "Oliepind & kølervæsketank", icon: "🛢️",
      what: "Dine to før-hver-tur motortjek: oliestand og kølervæskeniveau i det lukkede kredsløb.",
      where: "Oliepinden er et lyst (ofte gult) løkkehåndtag på siden af motoren. Ekspansionstanken er en halvgennemsigtig beholder med MIN/MAX-mærker, på eller ved motoren, med trykdæksel.",
      look: "Olie: mellem de to mærker og ikke mælkehvid (mælkehvid = vand i olien, ring til en mekaniker). Kølervæske: mellem MIN og MAX målt kold — åbn aldrig dækslet på en varm motor.",
      when: "Før hver tur. Tager 60 sekunder med lugen åben." },
    { id: "fuelsep", name: "Brændstoffilter / vandudskiller", icon: "⛽",
      what: "Et filter med en (ofte klar) skål i bunden, der fanger vand og snavs i dieselen, før den når motoren. Vand i dieselen er fjende nr. 1.",
      where: "Monteret på et skot i motorrummet, mellem tank og motor — kig efter en patron med en skål og en lille aftapningsskrue i bunden.",
      look: "Vand lægger sig som et tydeligt lag i bunden af skålen (diesel flyder oven på vand). Ethvert vandlag = åbn aftapningsskruen og luk det ud, til der kommer ren diesel.",
      when: "Et blik månedligt; skift elementet årligt / 400 t. Hold tanken fuld over vinteren, så den ikke kondenserer." },
    { id: "belts", name: "Kilerem", icon: "➰",
      what: "Remmen forrest på motoren, der trækker generatoren (ladning!) og cirkulationspumpen. Knækket rem = ingen ladning og en motor, der koger over.",
      where: "Forrest på motoren bag/under en afskærmning. Du kan se den løbe rundt om flere remskiver.",
      look: "Revner på tværs af ribberne, blanke skinnende sider eller sort gummistøv på motoren nedenunder = ved at være slidt. Tryk midt mellem remskiverne: ~1 cm eftergivenhed.",
      when: "Tjek årligt og ved enhver hvinende lyd. Hav en i reserve." },
    { id: "batteries", name: "Batterier & hovedafbrydere", icon: "🔋",
      what: "Typisk ét startbatteri (kun motor) og en forbrugsbank (køleskab, lys, instrumenter), plus evt. et bovpropelbatteri — holdt adskilt, så forbruget aldrig kan strande dig.",
      where: "I kasser under køjen i agterkahytten eller under dørken i salonen (varierer). De røde hovedafbrydere sidder typisk ved trappen eller i motorrummet.",
      look: "Poler spændt, ingen grøn/hvid ir, batterier spændt fast. Hvilespænding ~12,6 V+ = sundt; under 12,2 V = skal lades; kronisk lavt = batteriet ældes.",
      when: "Poler årligt, blik på spændingen hver tur, fuld opladning før vinteren." },
    { id: "bilge", name: "Bunden & lænsepumpen", icon: "🕳️",
      what: "Det laveste punkt inde i skroget, hvor alt vand samler sig, med en elektrisk pumpe og en svømmerafbryder, der skal starte automatisk.",
      where: "Under dørken — typisk en luge i salonens gulv og i motorrummet. Svømmerafbryderen sidder ved siden af pumpen.",
      look: "Bunden skal være tør (en kendt båd er en tør båd — nyt vand har altid en historie). Løft svømmerafbryderen med hånden: pumpen skal køre.",
      when: "Et blik hver tur; test svømmeren månedligt. Find ud af, hvor lænsevandet løber ud af skroget, så du kan genkende, når den pumper." },
    { id: "trimtabs", name: "Trimflaps", icon: "📐",
      what: "To stålplader på agterspejlets underkant, der presser agterenden op/stævnen ned — bruges til at komme hurtigere i plan og rette sejladsen op.",
      where: "Agterspejlets underkant, bagbord og styrbord, hver med en hydraulisk eller elektrisk cylinder.",
      look: "De skal køre jævnt i hele vandringen. Tjek den lille anode på hver flap, og at hængselsboltene ikke er løse.",
      when: "Funktionstest ved søsætning, anoder ved optagning." },
    { id: "thruster", name: "Bovpropel", icon: "↔️",
      what: "En propel i en tunnel gennem stævnen, der skubber stævnen sidelæns ved havnemanøvrer — Marex 370'erens bedste ven i sidevind.",
      where: "Tunnelen ses i stævnen under vandlinjen (ved optagning) — indvendigt sidder motoren under køjen/skabet forude.",
      look: "Ved optagning: propel fri for tang og fiskeline, den lille anode på drevet ikke tæret op. Indvendigt: forbindelser spændt, intet vand i rummet. Kør den kun i korte stød — den er ikke bygget til konstant drift.",
      when: "Anode og propel ved hver optagning; hurtig funktionstest ved søsætning." },
    { id: "heater", name: "Dieselvarmer", icon: "🔥",
      what: "Et Webasto/Eberspächer-fyr, der brænder diesel fra hovedtanken og blæser varm luft (eller varmer vand) gennem båden. Forlænger din sæson med måneder.",
      where: "Typisk i et cockpitskab eller motorrummet; du kan høre brændstofpumpen tikke, når det kører. Udstødningen er en lille gennemføring i skrogsiden.",
      look: "Hvid røg eller brændt lugt ved start er normalt i få sekunder; konstant røg, startsvigt eller udkobling = det soder til og skal serviceres.",
      when: "Kør 20+ min for fuld kraft månedligt (også om sommeren). Service når det driller — typisk hvert par hundrede driftstimer." },
  ],
};

STRINGS.da = {
  app_title: "Marex 370",
  tab_home: "Hjem", tab_service: "Service", tab_lists: "Lister", tab_todos: "Opgaver", tab_guide: "Guide",
  title_service: "Service", title_lists: "Tjeklister", title_todos: "Opgaver", title_guide: "Kend din båd", title_log: "Logbog",

  // hjem
  status: "Status", in_water: "🌊 I vandet", on_land: "🛠️ På land",
  btn_haulout: "Tag op", btn_launch: "Søsæt",
  engine_hours: "Motortimer", not_set: "— ikke sat —", updated_on: "opdateret {date}", btn_update: "Opdatér",
  needs_attention: "Kræver opmærksomhed", service_link: "Service ›",
  nothing_due: "Intet forfalder.", all_good: "Hun er i topform ✨",
  unlogged_hint: "{n} punkter har ingen historik endnu — registrér dem under Service.",
  quick_lists: "Hurtige tjeklister",
  chip_pretrip: "🧭 Før tur", chip_posttrip: "🏁 Efter tur", chip_monthly: "📅 Månedlig",
  logbook: "Logbog", all_link: "Alle ›",
  add_note_btn: "＋ Notat / foto", add_trip_btn: "＋ Registrér tur", add_fuel_btn: "＋ Tankning",
  start_here: "<strong>Start her 👋</strong> Indtast dine aktuelle motortimer (aflæs dem på displayet ved rattet), og gå derefter Service-fanen igennem og registrér cirka hvornår hvert punkt sidst blev lavet — et gæt er fint. Derefter fortæller appen dig, hvad der forfalder.",
  install_hint: "<strong>📲 Gør den til en app:</strong> tryk på Del-knappen nedenfor og vælg <strong>Føj til hjemmeskærm</strong>. Så får du et rigtigt app-ikon, fuld skærm, og den virker offline på vandet.",
  got_it: "Forstået",

  // status
  st_ok: "OK", st_soon: "Forfalder snart", st_overdue: "Overskredet", st_unknown: "Ikke registreret",
  d_overdue: "{n} dage over tiden", d_due: "forfalder {date}", h_left: "{n} t tilbage", h_overdue: "{n} t over tiden",
  no_interval: "Intet interval", log_first: "Registrér hvornår dette sidst blev lavet for at starte sporingen.",
  every: "Hver", as_needed: "Efter behov", hr: "t", yr: "år", mo: "mdr.",

  // service
  workshop: "værksted", last_lbl: "sidst",
  svc_footnote: "Intervallerne følger Volvo Pentas serviceskema for D-serien (det der kommer først: timer eller kalendertid). Justér efter din motors instruktionsbog, hvis den afviger.",
  add_service_btn: "＋ Tilføj dit eget servicepunkt",
  baseline_notice: "Indtast først dine motortimer under Hjem — timebaserede intervaller kan ikke spores uden.",
  expiry_card: "⏳ Udløbsdatoer",
  expiry_hint: "Ting med påtrykt udløbsdato: nødraketter, brandslukkere, gaspatroner til redningsveste, førstehjælp, EPIRB-batteri. Tilføj dem her, så dukker de op på Hjem i god tid.",
  add_expiry_btn: "＋ Tilføj udløbsdato",
  expires_on: "udløber {date}", expired_ago: "udløb for {n} dage siden",

  // tjeklister
  of_lbl: "{a} af {b}", checked_lbl: "{a}/{b} markeret", last_completed: "sidst gennemført {date}",
  log_completed_btn: "✓ Registrér som gennemført", check_all_btn: "Markér alle {n} punkter for at gennemføre",
  reset_boxes: "Nulstil afkrydsninger", reset_confirm: "Fjern alle markeringer?",
  completed_alert: "Registreret! ✓ Tjeklisten er nulstillet til næste gang.",
  items_lbl: "{n} punkter", list_completed_log: "{name} gennemført",

  // opgaver
  todo_ph: "Ny opgave… fx Køb ekstra impeller", add_btn: "Tilføj",
  todo_head: "Skal laves ({n})", done_head: "Færdige",
  todos_empty: "Intet på listen. Tilføj ting i samme øjeblik du spotter dem om bord — med et foto.",
  mark_done_btn: "✓ Markér som færdig", mark_undone_btn: "Markér som ikke færdig",
  delete_btn: "Slet", delete_todo_confirm: "Slet denne opgave?",
  todo_note_ph: "Detaljer, mål, varenumre…", added_lbl: "Oprettet", done_lbl: "færdig",

  // guide
  guide_intro: "<strong>Hvad er det, jeg kigger på?</strong> Letforståelige forklaringer på de dele, du møder på din Marex 370. Åbn hver enkelt og tag et foto af <em>din</em> båds udgave — næste sæson takker du dig selv.",
  yours: "📷 Din egen",
  yours_tip: "Tag et foto af denne del på din båd, så du altid ved hvordan den ser ud (og hvordan den så ud, da den var sund).",
  what_is: "Hvad det er", where_find: "Hvor den sidder", what_look: "Hvad du skal se efter", how_often: "Hvor ofte",

  // logbog
  log_empty: "Ingen registreringer endnu.",
  fuel_card: "⛽ Diesel i år", fuel_total: "{l} L", fuel_cost: " · {p} kr",
  fuel_rate: "≈ {r} L/t i snit (ud fra tankninger med timetal)",

  // formularer
  save: "Gem", cancel: "Annullér", history: "Historik",
  date_lbl: "Dato", hours_at_lbl: "Motortimer på tidspunktet", notes_lbl: "Noter", photos_lbl: "Fotos",
  optional_ph: "valgfrit",
  done_prefix: "Udført: {name}", usually_workshop: "typisk et værkstedsjob",
  no_history_tip: "Ingen historik endnu. Er du i tvivl om hvornår det sidst blev lavet, så registrér dit bedste gæt — eller registrér det som udført ved næste service.",
  delete_item_btn: "Slet dette punkt", delete_item_confirm: "Slet dette servicepunkt og dets historik?",
  md_note_ph: "Hvad blev lavet, reservedele, hvem gjorde det…",

  hours_title: "Motortimer",
  hours_tip: "Aflæs dem på motordisplayet ved rattet. Opdatér efter hver tur — alle timebaserede servicepåmindelser bygger på dette tal.",
  current_hours_lbl: "Aktuelle timer", hours_eg_ph: "fx 412",
  invalid_number: "Indtast et gyldigt tal.",
  lower_confirm: "Det er lavere end de nuværende {n} t. Gem alligevel?",
  hours_updated: "Motortimer opdateret",

  note_title: "Logbogsnotat",
  note_ph: "fx Underlig vibration ved 2500 o/min · tjekkede propellen, fandt et reb",
  note_empty_alert: "Skriv noget eller tilføj et foto.", photo_word: "Foto",

  trip_title: "Registrér tur", trip_where_lbl: "Tur / rute", trip_where_ph: "fx Havnen → Tunø og retur",
  hours_after_lbl: "Motortimer efter turen", trip_word: "Tur",

  fuel_title: "Tankning", liters_lbl: "Liter påfyldt", price_lbl: "Samlet pris, kr (valgfrit)",
  fuel_word: "Tankning", liters_invalid: "Indtast antal liter.",

  expiry_new_title: "Udløbsdato", name_lbl: "Hvad", expiry_name_ph: "fx Nødraketter (4 røde håndblus)",
  expiry_date_lbl: "Udløber", delete_expiry_confirm: "Slet denne udløbsdato?",

  // eget servicepunkt
  ns_title: "Nyt servicepunkt", ns_name_ph: "fx Olieskift på generator",
  group_lbl: "Gruppe", ns_hours_lbl: "Interval — motortimer (tom = intet)",
  ns_months_lbl: "Interval — måneder (tom = intet)", ns_why_lbl: "Noter", ns_why_ph: "Hvorfor / hvordan",
  add_item_btn: "Tilføj punkt", give_name: "Giv det et navn.",

  // indstillinger
  settings: "Indstillinger", boat_name_lbl: "Bådens navn", engine_lbl: "Motor", language_lbl: "Sprog / Language",
  backup_head: "Backup",
  backup_tip: "Data ligger kun på denne telefon. Eksportér en backup en gang imellem (fotos kommer ikke med i filen — de bliver på enheden).",
  export_btn: "⬇️ Eksportér backup", import_btn: "⬆️ Importér backup",
  danger_head: "Farezone", erase_btn: "Slet alle data",
  erase_c1: "Slet ALLE data? Det kan ikke fortrydes.",
  erase_c2: "Helt sikker? Servicehistorik, opgaver og fotos forsvinder.",
  import_confirm: "Erstat alle nuværende data med denne backup?",
  import_failed: "Import mislykkedes: {e}", not_backup: "Ikke en gyldig backupfil",
  storage_full: "Kunne ikke gemme data (lager fuldt?). Eksportér en backup fra Indstillinger.",

  // sæson
  season_water_log: "Søsat — i vandet 🌊", season_land_log: "Taget op — på land 🛠️",
  launch_prompt: "Hun er i vandet! Åbn forårets søsætningstjekliste?",
  haulout_prompt: "Taget op. Åbn tjeklisten for optagning & vinterklargøring?",

  // fotos
  viewer_delete: "Slet foto", viewer_close: "Luk",
  delete_photo_confirm: "Slet dette foto?", photo_failed: "Kunne ikke gemme fotoet: {e}",
  add_photo_lbl: "Tilføj",

  todo_done_log: "Opgave færdig: {t}",
  delete_log_confirm: "Slet denne logregistrering?", delete_entry_btn: "Slet registrering",
};

ILLUS_STRINGS.da = {
  imp_vanes1: "gummivinger — skal være", imp_vanes2: "bløde, ingen må mangle",
  imp_screws: "skruer i dækslet", imp_hub1: "messingnav (glider", imp_hub2: "på pumpeakslen)",
  imp_title: "Søvandspumpen med det runde dæksel afmonteret — impelleren sidder indeni",

  str_lid: "låg — åbnes med hånden", str_basket1: "kurv: man skal kunne", str_basket2: "se igennem skålen",
  str_from1: "fra søventil —", str_from2: "luk den før låget åbnes!", str_to: "til motorens pumpe",
  str_title: "Søvandsfilter — søvandet passerer kurven, før det når motoren",

  ano_shaft: "akselanode (krave)", ano_prop: "propel", ano_rudder: "ror", ano_disc: "roranode (skive)",
  ano_title: "Anoder tærer i stedet for dine metaldele — skift ved 50 % tæring",

  anf_hull: "skrog / vandlinjestribe", anf_wl: "vandlinje", anf_paint: "bundmaling — alt under vandlinjen",
  anf_title: "En ren, malet bund = fuld fart og lavere dieselforbrug",

  sea_handle1: "håndtag: ¼ omgang,", sea_handle2: "fast men smidigt",
  sea_hose1: "slange (dobbelte spændbånd", sea_hose2: "under vandlinjen)",
  sea_valve: "kuglehane i bronze", sea_thru: "skroggennemføring",
  sea_title: "En af disse vogter hvert hul i skroget — kend dem alle",

  shs_gearbox: "gearkasse", shs_seal1: "gummitætning — klem for at", shs_seal2: "'bøvse' luften ud ved søsætning",
  shs_shaft: "skrueaksel", shs_hull: "skrog — havet udenfor",
  shs_title: "Hvor akslen går ud gennem skroget. Skal være tør — dryp betyder service",

  oil_dip1: "oliepind (gul løkke):", oil_dip2: "olie mellem mærkerne, aldrig mælkehvid",
  oil_cap1: "trykdæksel — åbn aldrig", oil_cap2: "når motoren er varm!", oil_cool: "kølervæskeniveau, tjekkes kold",
  oil_title: "60-sekunders motortjekket før hver tur",

  fue_elem: "filterelement", fue_bowl1: "klar skål: diesel...", fue_bowl2: "...vand synker til bunds",
  fue_drain: "aftapningsskrue — luk vandet ud", fue_tank: "fra tanken",
  fue_title: "Vandudskiller — tjek skålen: ethvert vandlag tappes af",

  bel_crank: "krumtapsskive", bel_alt: "generator", bel_pump: "pumpe",
  bel_crack1: "se efter revner &amp;", bel_crack2: "sort støv nedenfor",
  bel_title: "Tryk midt mellem remskiverne — ca. 1 cm eftergivenhed er passende",

  bat_term1: "+ pol: spændt,", bat_term2: "ingen grøn ir",
  bat_house1: "forbrugsbank: køleskab,", bat_house2: "lys, instrumenter",
  bat_volt: "hvilespænding 12,6 V+ = sundt · under 12,2 V = oplad",
  bat_start: "START", bat_house: "FORBRUG",
  bat_title: "Adskilte banker, så køleskabet aldrig kan strande dig",

  bil_pump: "lænsepumpe", bil_float1: "svømmerafbryder — løft den", bil_float2: "med hånden: pumpen skal køre",
  bil_out: "ud gennem skrogsiden", bil_low: "skrogets laveste punkt — skal være TØRT",
  bil_title: "Nyt vand i bunden har altid en historie — find den",

  tri_ram: "hydraulikcylinder", tri_plate: "stålplade, hængslet", tri_anode: "lille anode på hver flap",
  tri_title: "Agterspejlet set bagfra — flapsene presser agterenden op og retter sejladsen op",

  thr_tunnel: "tunnel gennem stævnen", thr_prop: "propel + lille anode — hold fri for tang &amp; liner",
  thr_wl: "vandlinje",
  thr_title: "Stævnen set fra siden — bovpropellen skubber stævnen sidelæns",

  hea_burn1: "brænder — diesel fra", hea_burn2: "hovedtanken",
  hea_duct: "varmluftkanaler til kahytterne", hea_exh: "udstødning gennem skrogsiden",
  hea_pump: "brændstofpumpe (tikker når den kører)",
  hea_title: "Kør den hårdt 20 min om måneden, så den aldrig soder til",

  rud_bear1: "rorleje &amp; styrearm", rud_bear2: "(inde i båden)",
  rud_stock1: "rorstamme — tag fat i", rud_stock2: "bladet &amp; mærk efter slør", rud_blade: "rorblad",
  rud_title: "Ved optagning: skub til roret med hånden — slør = slidt leje",
};
