/* English content + UI strings.
   Intervals follow the Volvo Penta D4/D6 operator's manual rhythm
   (oil/filter 200 h or 12 months, impeller 12 months, coolant 4 years, etc.)
   plus standard BoatUS-style commissioning / winterization practice.
   IMPORTANT: ids must match content-da.js — saved state is keyed by them. */

CONTENT.en = {
  groups: [
    { id: "engine",    name: "Engine",             icon: "⚙️" },
    { id: "underwater",name: "Underwater & drive", icon: "🌊" },
    { id: "systems",   name: "Boat systems",       icon: "🔌" },
    { id: "safety",    name: "Safety gear",        icon: "🦺" },
  ],

  services: [
    // ENGINE — Volvo Penta D4/D6
    { id: "oil",        group: "engine", name: "Engine oil & filter",
      intervalHours: 200, intervalMonths: 12,
      why: "Fresh oil is the cheapest engine insurance there is. Old oil turns acidic and wears the engine from the inside. Change while the engine is warm so the old oil drains fully." },
    { id: "fuelfilter", group: "engine", name: "Fuel filters (engine + water separator)",
      intervalHours: 400, intervalMonths: 12,
      why: "Diesel attracts water and grows bacteria ('diesel bug'). The filters and the water-separator bowl are what stand between that and your injectors. Drain the separator bowl whenever you see water in it." },
    { id: "impeller",   group: "engine", name: "Raw water impeller",
      intervalMonths: 12,
      why: "A small rubber paddle wheel that pumps seawater through the engine cooling system. When it fails the engine overheats within minutes. Cheap part, big consequences — replace every season and keep a spare aboard." },
    { id: "belts",      group: "engine", name: "Drive belts — inspect & tension",
      intervalMonths: 12,
      why: "Belts drive the alternator and circulation pump. Look for cracks, glazing and black rubber dust below the belt (a wear sign). Press midway between pulleys: about 1 cm of give is right." },
    { id: "airfilter",  group: "engine", name: "Air filter",
      intervalHours: 400, intervalMonths: 24,
      why: "A clogged filter makes the engine smoke and lose power. Quick visual check yearly, replace when dirty." },
    { id: "coolant",    group: "engine", name: "Coolant (VCS) replace",
      intervalMonths: 48, pro: true,
      why: "The closed-circuit coolant (Volvo's yellow VCS) loses its corrosion protection over time. Check the level at every trip; replace the fluid every 4 years." },
    { id: "valves",     group: "engine", name: "Valve clearance check",
      intervalHours: 1000, intervalMonths: 60, pro: true,
      why: "A workshop job on the Volvo schedule. Worth booking together with a big service." },
    { id: "heatex",     group: "engine", name: "Heat exchanger & aftercooler service",
      intervalHours: 1000, intervalMonths: 48, pro: true,
      why: "Seawater slowly scales up the cooling cores. A workshop cleans and pressure-tests them. Skipping this is a classic cause of creeping overheating on older D-series engines." },
    { id: "enginezinc", group: "engine", name: "Engine zinc anodes (cooling system)",
      intervalMonths: 12,
      why: "Small zinc pencils screwed into the heat exchanger — the engine's own sacrificial anodes, protecting the cooling circuit from corrosion. Unscrew and check: more than half gone = replace. The Volvo workshop fits new ones at the big services." },

    // UNDERWATER & DRIVE
    { id: "anodes",     group: "underwater", name: "Sacrificial anodes",
      intervalMonths: 12,
      why: "Zinc/aluminium lumps on the shaft, rudder, trim tabs and thruster that corrode so your metal parts don't. Replace any that are more than half eaten — they are cheap insurance. Never paint over them." },
    { id: "antifoul",   group: "underwater", name: "Antifouling paint",
      intervalMonths: 12,
      why: "Keeps barnacles and weed off the hull. A fouled hull can cost you several knots and a lot of diesel. Repaint (or at least touch up) every spring before launch." },
    { id: "propshaft",  group: "underwater", name: "Propeller & shaft inspection",
      intervalMonths: 12,
      why: "Check the prop for dings (they cause vibration), and look for fishing line wrapped at the shaft seal — it destroys seals. Grab the shaft and feel for play in the cutless bearing." },
    { id: "shaftseal",  group: "underwater", name: "Shaft seal / stern gland",
      intervalHours: 500, intervalMonths: 60, pro: true,
      why: "Where the propeller shaft exits the hull. The Volvo rubber seal must be 'burped' (squeezed to release air) every launch, and replaced roughly every 5 years. It should run dry — water here goes straight in the bilge." },
    { id: "seacocks",   group: "underwater", name: "Seacocks — exercise & grease",
      intervalMonths: 12,
      why: "Every valve on a hole in the hull. Open and close each one fully a few times so they never seize — a seacock you can't close in an emergency is a sinking risk. Grease at haul-out." },
    { id: "hoses",      group: "underwater", name: "Hoses & clamps below waterline",
      intervalMonths: 12,
      why: "Squeeze hoses (soft or cracked = replace) and check every clamp is tight and not rusty. Critical hoses below the waterline should be double-clamped." },
    { id: "thruster",   group: "underwater", name: "Bow thruster — anode, prop & oil",
      intervalMonths: 12,
      why: "The thruster leg has its own small anode that vanishes fast. Check the propeller spins free of weed and line, and check gear oil if your model allows." },
    { id: "rudder",     group: "underwater", name: "Rudder & steering check",
      intervalMonths: 12,
      why: "At haul-out: push the rudder by hand — noticeable play means worn bearings. Turn the wheel lock-to-lock and check hydraulic fluid level at the helm pump." },

    // BOAT SYSTEMS
    { id: "batteries",  group: "systems", name: "Batteries — terminals & condition",
      intervalMonths: 12,
      why: "Clean and grease terminals, check they're strapped tight, and verify a rested voltage of ~12.6 V+. Most Marex boats have a separate start battery and house bank — check both." },
    { id: "freshwater", group: "systems", name: "Freshwater system flush & sanitize",
      intervalMonths: 12,
      why: "After winter, flush out the antifreeze and sanitize the tank (e.g. with a chlorine solution), then rinse. Also check the pump doesn't cycle when no tap is open — that means a leak." },
    { id: "toilet",     group: "systems", name: "Toilet & holding tank service",
      intervalMonths: 12,
      why: "Lubricate the pump/valves, check the joker valve, rinse the holding tank. Treat hoses with respect — old sanitation hose is the usual source of smells." },
    { id: "heater",     group: "systems", name: "Diesel heater (Webasto/Eberspächer) service",
      intervalMonths: 12, pro: true,
      why: "Common in Marex boats. Run it at full power 20+ minutes monthly even in summer so it doesn't coke up; have it serviced when it starts smoking or smelling." },
    { id: "gas",        group: "systems", name: "Gas system leak test",
      intervalMonths: 12, pro: true,
      why: "If you have a gas stove: hoses have a printed expiry date, and the system should be leak-tested (a professional check every couple of years is money well spent). Gas sinks into the bilge — treat it seriously." },
    { id: "windlass",   group: "systems", name: "Anchor windlass & chain",
      intervalMonths: 12,
      why: "Grease the windlass, run the chain out and inspect it, and re-mark the length markings. Check the chain-to-anchor shackle is seized with wire." },
    { id: "trimtabs",   group: "systems", name: "Trim tabs check",
      intervalMonths: 12,
      why: "Run them full up/down and watch them move. Check hydraulic lines, hinge pins, and the small anodes on the tabs themselves." },
    { id: "canvas",     group: "systems", name: "Canvas, hatches & seal lubrication",
      intervalMonths: 12,
      why: "Silicone-grease the rubber seals on hatches and the sliding roof, treat zippers, and check drains in the cockpit aren't blocked." },

    // SAFETY
    { id: "extinguisher", group: "safety", name: "Fire extinguishers check",
      intervalMonths: 12,
      why: "Gauge in the green, pin sealed, no corrosion. Turn powder extinguishers upside down and shake so the powder doesn't cake. Professional service per the label." },
    { id: "lifejackets", group: "safety", name: "Lifejackets — inspect & service",
      intervalMonths: 12,
      why: "For inflatables: check the gas cylinder is screwed tight and not corroded, and the auto-cartridge is in date. Most makers want a full service every 1–2 years." },
    { id: "flares",     group: "safety", name: "Flares & signals expiry",
      intervalMonths: 12,
      why: "Flares expire after 3–4 years. Check dates each spring and replace expired ones (hand them in — don't bin them)." },
    { id: "firstaid",   group: "safety", name: "First aid kit restock",
      intervalMonths: 12,
      why: "Check expiry on everything, restock plasters and seasickness tablets before the season." },
    { id: "alarms",     group: "safety", name: "Smoke / gas / CO alarms",
      intervalMonths: 12,
      why: "Press-test the alarms and change batteries every spring. A diesel heater plus a closed boat makes a CO alarm cheap life insurance." },
  ],

  checklists: [
    {
      id: "buy", name: "Before you buy / handover", icon: "🔑",
      desc: "The big one — walk the whole boat before money changes hands. Take your time, take photos of every fault, and write down anything that needs negotiating. Bring a torch, an old towel, work gloves and a power bank. Honestly: for a boat this size, also pay a marine surveyor — this list makes you a sharp second pair of eyes, not a replacement for one.",
      sections: [
        { name: "Paperwork first — before you pay a krone", items: [
          { id: "owner",   text: "Seller is the real owner & boat is debt-free", sub: "Match the seller's ID to the ownership papers. A boat can carry a loan/lien (in DK check the Skibsregister / 'pant'). No clear title = walk away — the debt follows the boat, not the seller." },
          { id: "vat",     text: "VAT (moms) paid & papers exist", sub: "Ask for the original invoice or VAT-paid document. Within the EU a boat without proof of VAT can cost you 25% of its value later. Non-negotiable." },
          { id: "ce",      text: "CE plate & HIN/CIN hull number present", sub: "Find the builder's plate (usually in the cockpit locker or helm) and the hull number stamped on the transom. Check they match the papers — mismatches mean a hidden history." },
          { id: "hours",   text: "Engine hours match the logbook & service records", sub: "Read the hours off the engine display. Compare with invoices. ~150–200 h/year is normal; very low hours on an old boat isn't always good (seals dry out, diesel ages)." },
          { id: "service", text: "Service history is complete & recent", sub: "Ask for every invoice. Look for regular oil/impeller changes and a recent major service. Gaps = budget for catch-up work. (Your boat's last big Volvo service is already logged in this app.)" },
          { id: "manuals", text: "All manuals, keys, remotes & handover items present", sub: "Engine book, electronics manuals, both ignition keys, thruster/heater remotes, canvas, original sails of equipment lists. Missing keys/remotes are expensive to replace." },
          { id: "extras",  text: "Inventory list agreed in writing", sub: "Walk the boat with the ad's equipment list. Dinghy, outboard, anchor, fenders, electronics, cushions — tick each one off and write it into the contract so nothing 'disappears' before handover." },
        ]},
        { name: "Hull & underwater (ideally ashore)", items: [
          { id: "gel",     text: "Hull sides & gelcoat — cracks, repairs, impacts", sub: "Sight down the hull from bow and stern in raking light. Star-shaped cracks = impact; long straight cracks = stress. Mismatched gelcoat colour = a repair you should ask about." },
          { id: "osmosis", text: "Underwater hull — blisters / osmosis & moisture", sub: "Run your hand over the bottom for blisters (bubbles under the paint). A surveyor uses a moisture meter here — the single best reason to hire one. Widespread blistering is a five-figure repair." },
          { id: "keel",    text: "Keel, skeg & running gear undamaged", sub: "Look for grounding damage at the lowest points. Check the prop for dings and the shaft for straightness (a bent shaft shows as vibration later)." },
          { id: "anodes",  text: "Anodes & no signs of galvanic/stray-current damage", sub: "Anodes half-gone is normal. But pink/eaten bronze on the prop or fittings = stray current in the marina, which quietly destroys underwater metal. Ask how the boat is wired to shore power." },
          { id: "rudder",  text: "Rudder & cutless bearing play", sub: "Grab the rudder and the prop and try to wiggle them. More than slight movement = worn bearings/cutless bearing. Note it for negotiation." },
          { id: "thru",    text: "Through-hulls & seacocks all sound", sub: "Count them and check each bronze fitting for pink/eaten metal and each valve moves. Tired seacocks are a haul-out job to replace." },
        ]},
        { name: "Deck, windows & the sliding roof", items: [
          { id: "deckcrack",text: "Deck & cockpit — soft spots, crazing, repairs", sub: "Walk every part of the deck and press hard, especially around fittings. A spongy or 'crunchy' feel = wet core, an expensive structural repair. Listen for a dull thud vs a sharp tap." },
          { id: "windows", text: "Windows & big glass — seals, leaks, fogging", sub: "The Marex's large windows are a known leak point. Look for water stains, fogged double-glazing and perished rubber seals. Check the headlining below each window for brown tide-marks." },
          { id: "roof",    text: "Electric sliding roof — full open & close", sub: "Run it fully both ways. Listen for the motor straining, watch it doesn't jam, and check the seals and drain channels. A stuck sunroof is a costly Marex-specific repair." },
          { id: "fittings",text: "Cleats, rails, stanchions & windlass solid", sub: "Push/pull every cleat and the pulpit. Movement = loose backing plates and possible leaks. Run the anchor windlass out and back under power." },
          { id: "canvas",  text: "Canvas, sprayhood & cockpit cover condition", sub: "Check zips run, stitching isn't rotten, and clears (plastic windows) aren't cracked yellow. A full new canvas set is a serious bill." },
        ]},
        { name: "Cabin & interior", items: [
          { id: "smell",   text: "First impression — smell the boat", sub: "Step below and just breathe. Damp/musty = water getting in somewhere. Diesel = a fuel leak. Sewage = tired holding-tank hoses. Your nose finds problems before your eyes." },
          { id: "damp",    text: "Headlining, lockers & corners — water staining", sub: "Open every locker and look in the corners and under cushions for brown stains, mould or rust streaks. Lift floorboards and check for standing water or a tide-line in the bilge." },
          { id: "soft",    text: "Floors & bulkheads — soft spots & movement", sub: "Walk the sole and press bulkhead corners. Sponginess or cracking around bulkhead tabbing = structural issues. Take photos." },
          { id: "uph",     text: "Upholstery, woodwork & trim condition", sub: "Cosmetic, but re-upholstery and water-stained veneer are real money. Note anything you'd want replaced for negotiation." },
        ]},
        { name: "Engine bay — COLD, before it's started", items: [
          { id: "first",   text: "Insist on a genuinely cold start later — check it's cold now", sub: "Touch the block. A seller who 'warmed it up for you' may be hiding a hard starter. You want to witness the very first cold start yourself (next section)." },
          { id: "oil",     text: "Engine oil — level, colour & not milky", sub: "Pull the dipstick. Black is fine. Milky/coffee-coloured = water in the oil (failed head gasket or oil cooler) — a major red flag. Smell it: diesel smell = fuel dilution." },
          { id: "coolant", text: "Coolant — level, colour & clean", sub: "Check the expansion tank (cold only). Oily film on top or brown sludge = internal problems. Level should be at the mark." },
          { id: "belts",   text: "Belts, hoses & mounts — condition", sub: "Squeeze hoses (hard/cracked = old), check belts for cracks and dust, and look at the rubber engine mounts for collapse or oil-soaking." },
          { id: "corr",    text: "Corrosion, leaks & general bay condition", sub: "Heavy rust or salt crust = possible past flooding or a leaking raw-water system. Look under the engine for fresh oil/coolant/fuel pooling. A clean, dry bay is a well-kept boat." },
          { id: "raw",     text: "Raw-water strainer & seacock", sub: "Strainer bowl clean, raw-water seacock present and movable. Trace the hose so you know the engine's seawater path." },
        ]},
        { name: "Systems at the dock (shore power on)", items: [
          { id: "batt",    text: "Batteries & charger — age, voltage, charging", sub: "Ask the battery age (4–6 yrs typical life). Check the charger actually charges (voltage rises). A new battery bank is a four-figure cost." },
          { id: "elec",    text: "Every electrical item — switch it ALL on", sub: "Go switch by switch on the panel: every light (nav + cabin), horn, wipers, blower, USB sockets. Anything dead is a fault to log." },
          { id: "nav",     text: "Electronics power up — chartplotter, VHF, depth, radar, autopilot", sub: "Turn each on and let it find a signal. VHF: do a radio check. Some only fail under way (test again at sea). Replacement electronics are pricey." },
          { id: "fridge",  text: "Fridge / freezer cools down", sub: "Switch it on early in your visit and come back an hour later — it should be noticeably cold. Compressor fridges fail expensively." },
          { id: "water",   text: "Freshwater — pump, taps, hot water & no leaks", sub: "Run every tap hot and cold. Pump should stop when taps are closed (cycling = a leak). Check the water heater works on shore power." },
          { id: "toilet",  text: "Toilet & holding tank work and don't smell", sub: "Flush it, check it pumps and holds. Sniff the hoses. Sanitation work is the job nobody wants." },
          { id: "heater",  text: "Diesel heater (Webasto/Eberspächer) fires up", sub: "Run it to full heat. White smoke and a strong fuel smell that doesn't clear, or a shutdown, means it's coking up — budget for service. Common and pricey on these boats." },
          { id: "gas",     text: "Gas (if fitted) — stove lights, no leaks, in-date hoses", sub: "Light the stove. Check the regulator and that the hose isn't past its printed date. Smell for gas in the locker and bilge." },
        ]},
        { name: "The cold start (watch it yourself)", items: [
          { id: "crank",   text: "Cranks & fires quickly without excessive smoke", sub: "It should catch within a few seconds. Long cranking = tired batteries, glow plugs or fuel issues. Stand at the stern and watch the exhaust as it fires." },
          { id: "smoke",   text: "Exhaust smoke colour at startup", sub: "A short puff is normal. Then: BLUE = burning oil (worn engine), WHITE that won't clear = water/coolant or unburnt fuel, BLACK = over-fuelling. Persistent colour is a serious flag." },
          { id: "water",   text: "Cooling water out of the exhaust within seconds", sub: "Look over the transom — a steady stream of water should appear almost immediately. None = impeller/pump problem, and the engine is overheating right now." },
          { id: "idle",    text: "Idles smoothly, no warning lights or alarms", sub: "Let it settle. It should idle evenly with no rattles, no warning lamps, no buzzers. Note any vibration or knocking." },
          { id: "gauges",  text: "Gauges come alive — oil pressure & charging", sub: "Oil pressure should rise immediately, the alternator should charge (voltage up), temperature should climb slowly to normal and then hold." },
        ]},
        { name: "Sea trial — the most important hour", items: [
          { id: "warm",    text: "Warm up gently, then check temperature holds", sub: "Don't gun a cold engine. Once warm, the temperature gauge should sit rock-steady. A creeping or fluctuating temperature = cooling problem (scaled heat exchanger, tired impeller)." },
          { id: "wot",     text: "Reaches rated max RPM at wide-open throttle", sub: "Push to full throttle in open water. The engine MUST reach its rated max rpm (check the Volvo plate — roughly 3500 rpm for a D6). Falling short = tired engine, fouled bottom or wrong prop. Over-revving = worn/under-pitched prop." },
          { id: "load",    text: "Under full load: oil pressure steady, no overheating, charging", sub: "Hold near full throttle a few minutes and watch every gauge. Pressure steady, temperature stable, volts charging. This is where a tired engine finally shows itself." },
          { id: "smokeload",text:"No heavy smoke under load", sub: "Glance back at the exhaust at speed. A clear engine stays clear under load. Black/blue smoke when you push it = injectors, turbo or worn internals." },
          { id: "gears",   text: "Gear shifts — clean into forward & reverse, no clunk", sub: "Shift F-N-R a few times. Engagement should be prompt and smooth. Heavy clunking, delay or slipping = gearbox/linkage attention." },
          { id: "steer",   text: "Steering lock-to-lock — smooth, no play, no leaks", sub: "At low speed turn full circles both ways. Check the hydraulic helm for free play and look at the ram for fluid leaks. Then check it tracks straight hands-off at cruise." },
          { id: "thruster",text: "Bow thruster gives a strong, even push", sub: "Short bursts both ways. Weak or noisy = worn prop, low battery or a fouled tunnel. Don't hold it on — it overheats." },
          { id: "tabs",    text: "Trim tabs change the ride", sub: "Work them up/down under way and feel the bow/stern respond. No effect = seized rams or a hydraulic leak." },
          { id: "vib",     text: "Feel & listen for vibration at all speeds", sub: "Sweep slowly through the rev range. A vibration that comes and goes at a certain rpm = prop, shaft or engine-mount issue. Note the rpm it happens at." },
          { id: "navsea",  text: "Electronics & autopilot under way", sub: "Now test the chartplotter, depth, radar and especially the autopilot while moving — vibration and load expose faults the dock test hides." },
          { id: "leaksea", text: "Go below at speed — check for leaks & water ingress", sub: "While someone drives at cruise, open the engine bay and lift the floorboards. The bilge should stay dry. Water appearing only under way points to the shaft seal or a hose under pressure." },
        ]},
        { name: "After the trial & closing the deal", items: [
          { id: "hot",     text: "Hot engine — recheck for new leaks", sub: "With the engine hot and just stopped, look again for oil, fuel, coolant or exhaust leaks that only show when everything's expanded and under pressure." },
          { id: "reoil",   text: "Re-pull the dipstick — level, no fuel/water dilution", sub: "Oil shouldn't have risen (fuel getting in) or gone milky (water). Smell it again." },
          { id: "list",    text: "Write your fault list & get repair quotes", sub: "Everything you photographed: total it up. Real quotes for the big items (windows, heater, electronics) are your negotiation leverage." },
          { id: "survey",  text: "Compare against the surveyor's report", sub: "If you hired a surveyor (recommended for a boat this size), make sure their findings and yours line up before you commit." },
          { id: "negotiate",text:"Agree who fixes what, in writing", sub: "Price reduction or seller-fixes-before-handover — get it in the contract, not a handshake. Don't pay the balance until agreed work is verified done." },
          { id: "handover",text: "Final handover — walk the systems together", sub: "Have the seller show you how to start, the seacock locations, battery switches, heater, thruster and winterising quirks. Then log your engine hours in this app as your starting point." },
        ]},
      ],
    },
    {
      id: "launch", name: "Spring — onto the water", icon: "🌱",
      desc: "Launch & commissioning. Work top-down: everything on land first, then the in-water checks the moment she floats.",
      sections: [
        { name: "On land, before launch", items: [
          { id: "af",      text: "Antifouling painted / touched up", sub: "Hull clean, sanded where flaking, fresh coat applied. Don't paint the anodes!" },
          { id: "anodes",  text: "Anodes checked — replaced if >50% gone", sub: "Shaft, rudder, trim tabs, bow thruster." },
          { id: "hull",    text: "Hull, prop, shaft & rudder inspected", sub: "Dings in prop, play in shaft/rudder, damage or blisters in gelcoat." },
          { id: "seacock", text: "All seacocks exercised & greased", sub: "Open/close each fully a few times. They must move freely." },
          { id: "hoses",   text: "Hoses & clamps below waterline checked", sub: "Squeeze test, tighten clamps, double clamps on critical hoses." },
          { id: "impeller",text: "Impeller fitted & raw water system reconnected", sub: "If you removed it for winter. Light dish soap on the blades helps the dry start." },
          { id: "engine",  text: "Engine: oil level, coolant level, belts", sub: "Oil between marks, coolant between MIN/MAX (cold), belts firm without cracks." },
          { id: "batt",    text: "Batteries connected & fully charged", sub: "Terminals tight and greased. Check voltage ~12.6 V+ rested." },
          { id: "plugs",   text: "DRAIN PLUGS IN", sub: "The classic. Check every drain plug is fitted before she touches water." },
        ]},
        { name: "In the water — first 10 minutes", items: [
          { id: "leaks",   text: "Leak check at shaft seal, seacocks & through-hulls", sub: "Go below immediately and look. A dry bilge should stay dry." },
          { id: "burp",    text: "Shaft seal burped (Volvo rubber seal)", sub: "Squeeze the rubber boot until water spurts out — this releases trapped air so it self-lubricates." },
          { id: "start",   text: "Engine started — raw water out of exhaust within seconds", sub: "No water = stop immediately. Check seacock open and strainer primed." },
          { id: "gauges",  text: "Oil pressure, temperature & charging normal", sub: "Watch the gauges for the first few minutes at the dock." },
          { id: "steer",   text: "Steering lock-to-lock, throttle & gear tested", sub: "Forward/reverse briefly against the lines." },
          { id: "thruster",text: "Bow thruster & trim tabs tested", sub: "" },
        ]},
        { name: "Commissioning the boat", items: [
          { id: "water",   text: "Freshwater system flushed & refilled", sub: "Flush all antifreeze out of every tap (hot + cold) before filling for use." },
          { id: "elec",    text: "Nav lights, horn, wipers, VHF tested", sub: "" },
          { id: "bilge",   text: "Bilge pump tested — auto float & manual", sub: "Lift the float switch by hand and listen for the pump." },
          { id: "safety",  text: "Safety gear aboard & in date", sub: "Lifejackets, extinguishers, flares, first aid kit." },
          { id: "lines",   text: "Mooring lines, fenders & anchor rigged", sub: "" },
          { id: "hours",   text: "Engine hours logged as season start", sub: "Update the hours on the Home tab." },
        ]},
      ],
    },
    {
      id: "haulout", name: "Autumn — up from the water", icon: "❄️",
      desc: "Haul-out & winterization. The golden rule: no water anywhere it can freeze, no half-empty diesel tank, no flat batteries.",
      sections: [
        { name: "In the water, before haul-out", items: [
          { id: "fuel",    text: "Diesel tank filled + biocide added", sub: "A full tank can't condensate water on the walls. Add a diesel bug treatment." },
          { id: "oil",     text: "Engine oil & filter changed (warm engine)", sub: "Old acidic oil should not sit in the engine all winter. Run her warm first." },
          { id: "holding", text: "Holding tank pumped out & rinsed", sub: "" },
        ]},
        { name: "At haul-out", items: [
          { id: "wash",    text: "Hull pressure-washed immediately", sub: "Growth comes off 10× easier while still wet." },
          { id: "inspect", text: "Hull, prop, shaft, rudder & anodes inspected", sub: "Photograph anything suspicious now — easy to forget by spring. Note anode condition." },
        ]},
        { name: "On land — engine & systems", items: [
          { id: "raw",     text: "Raw water system winterized", sub: "Close seacock, open strainer, run engine on antifreeze poured into the strainer until it runs coloured out of the exhaust." },
          { id: "imp",     text: "Impeller removed (or noted as left in)", sub: "Stored flat it keeps its shape. Write down what you did so spring-you knows." },
          { id: "fresh",   text: "Freshwater system drained + antifreeze", sub: "Tank, pump, water heater, all taps (hot & cold), deck shower. Non-toxic propylene glycol only." },
          { id: "toilet",  text: "Toilet & holding tank winterized", sub: "Pump antifreeze through the toilet and leave some in the bowl & tank." },
          { id: "batt",    text: "Batteries fully charged + disconnected or on maintainer", sub: "A charged battery doesn't freeze; a flat one can crack at -10 °C." },
          { id: "coolant", text: "Coolant antifreeze strength checked", sub: "The closed circuit should protect to at least -25 °C." },
        ]},
        { name: "On land — boat", items: [
          { id: "remove",  text: "Electronics, lifejackets, cushions, food & liquids removed", sub: "Anything that can freeze, mold or get stolen goes home." },
          { id: "fridge",  text: "Fridge defrosted & propped open", sub: "" },
          { id: "vent",    text: "Boat ventilated + moisture absorbers placed", sub: "Open lockers and floor hatches so air circulates." },
          { id: "grease",  text: "Seacocks greased, left as the yard advises", sub: "" },
          { id: "cover",   text: "Cover fitted & checked for chafe", sub: "Check it again after the first storm." },
          { id: "hours",   text: "Engine hours logged as season end", sub: "Update the hours on the Home tab." },
        ]},
      ],
    },
    {
      id: "pretrip", name: "Before every trip", icon: "🧭",
      desc: "The 5-minute check before you cast off. Resets itself automatically so it's ready every time.",
      autoReset: true,
      sections: [
        { name: "Engine bay (open the hatch!)", items: [
          { id: "oil",    text: "Oil level between the marks", sub: "" },
          { id: "coolant",text: "Coolant between MIN/MAX", sub: "Only check cold." },
          { id: "look",   text: "Look & sniff: no fuel, oil or water where it shouldn't be", sub: "30 seconds with eyes and nose finds most problems early." },
          { id: "strainer",text:"Sea strainer clear", sub: "Glance through the clear bowl — no weed or plastic bags." },
        ]},
        { name: "Boat", items: [
          { id: "bilge",  text: "Bilge dry, pump on auto", sub: "" },
          { id: "fuel",   text: "Enough diesel: ⅓ out, ⅓ home, ⅓ reserve", sub: "" },
          { id: "batt",   text: "Battery switches on, voltage OK", sub: "" },
          { id: "weather",text: "Weather & wind forecast checked", sub: "" },
          { id: "plan",   text: "Told someone where you're going", sub: "" },
          { id: "jackets",text: "Lifejackets out — everyone aboard has one", sub: "" },
        ]},
        { name: "After engine start", items: [
          { id: "water",  text: "Raw water flowing from exhaust", sub: "Look over the side within seconds of starting." },
          { id: "gauges", text: "Oil pressure & charging normal", sub: "" },
          { id: "lines",  text: "Fenders in, no lines trailing in the water", sub: "A line in the prop ends the trip." },
        ]},
      ],
    },
    {
      id: "posttrip", name: "After every trip", icon: "🏁",
      desc: "Leave the boat so the next trip starts easy. Resets automatically.",
      autoReset: true,
      sections: [
        { name: "Securing the boat", items: [
          { id: "hours",  text: "Engine hours updated in the app", sub: "Home tab → update hours. This drives all the service reminders." },
          { id: "lines",  text: "Mooring lines & fenders set for coming weather", sub: "" },
          { id: "bilge",  text: "Bilge checked dry", sub: "" },
          { id: "seacocks",text:"Toilet & galley seacocks closed if leaving the boat", sub: "" },
          { id: "shore",  text: "Shore power connected, charger on", sub: "" },
          { id: "fridge", text: "Perishables out of the fridge (if away >2 days)", sub: "" },
          { id: "rinse",  text: "Quick freshwater rinse of cockpit & stainless", sub: "Salt is what ages the boat." },
          { id: "canvas", text: "Canvas/covers on, hatches closed, boat locked", sub: "" },
        ]},
      ],
    },
    {
      id: "monthly", name: "Monthly in season", icon: "📅",
      desc: "A 30-minute round once a month keeps surprises away. Resets automatically when you complete it.",
      autoReset: true,
      sections: [
        { name: "The monthly round", items: [
          { id: "strainer",text:"Sea strainer opened & cleaned", sub: "Close the seacock first, clean the basket, reopen — then check water flows when the engine starts." },
          { id: "belts",  text: "Belt glance: tension OK, no black dust", sub: "" },
          { id: "clamps", text: "Engine bay hose clamps eyeballed", sub: "" },
          { id: "batt",   text: "Battery terminals & charger state checked", sub: "" },
          { id: "bilgep", text: "Bilge pump float switch tested by hand", sub: "" },
          { id: "anode",  text: "Visible anodes checked (trim tabs / thruster if reachable)", sub: "" },
          { id: "chafe",  text: "Mooring lines checked for chafe", sub: "" },
          { id: "ext",    text: "Fire extinguisher gauges in the green", sub: "" },
          { id: "heater", text: "Diesel heater run 20 min at full power", sub: "Keeps it from coking up." },
          { id: "wash",   text: "Boat washed, drains & scuppers clear", sub: "" },
        ]},
      ],
    },
  ],

  guide: [
    { id: "impeller", name: "Raw water impeller", icon: "🌀",
      what: "A star-shaped rubber wheel inside a bronze pump on the front/side of the engine. It sucks seawater in through the hull and pushes it through the heat exchanger to cool the engine.",
      where: "On the Volvo Penta D-series it sits behind a round cover plate with 4–6 screws on the raw water pump, low at the front of the engine. Follow the hose from the sea strainer — it ends at the pump.",
      look: "Rubber blades should be supple and unbroken. Cracked, stiff or missing blades = replace now (and find the missing bits in the heat exchanger before they block it).",
      when: "Replace every 12 months. Always keep a spare impeller kit aboard." },
    { id: "strainer", name: "Sea strainer", icon: "🧺",
      what: "A filter with a clear bowl that catches weed, plastic and jellyfish before they reach the engine's cooling water pump.",
      where: "Between the engine's raw water seacock and the engine, in the engine bay — usually mounted on a bulkhead near the engine, with a transparent lid or bowl.",
      look: "You should be able to see through it. Weed, mud or a collapsed basket means cleaning time. Close the seacock before opening it!",
      when: "Glance before every trip, clean monthly in season." },
    { id: "anodes", name: "Sacrificial anodes", icon: "🧲",
      what: "Blocks of zinc (salt water) or aluminium that corrode away on purpose, protecting your propeller, shaft, rudder and trim tabs from galvanic corrosion.",
      where: "On the shaft (a collar), on the rudder, on each trim tab, and a small ring or disc on the bow thruster leg. There may also be a pear-shaped hull anode.",
      look: "A healthy anode is rough and matte from corroding. Shiny untouched anodes might not have good contact. More than ~50% eaten = replace.",
      when: "Check at every haul-out, replace yearly or at 50% gone. Never paint them." },
    { id: "antifoul", name: "Antifouling", icon: "🎨",
      what: "Biocide paint on the hull bottom that stops barnacles and weed from growing. A fouled hull steals speed and burns extra diesel.",
      where: "Everything below the waterline. The prop and shaft can get their own special prop coating.",
      look: "At haul-out: if the bottom was slimy/green but rinses clean, the paint is working. Barnacles stuck on = time for a fresh coat (or a better paint).",
      when: "Repaint each spring before launch. Check local rules — some Baltic harbours restrict paint types." },
    { id: "seacocks", name: "Seacocks & through-hulls", icon: "🔩",
      what: "Ball valves on every hole in the hull: engine cooling intake, toilet in/out, galley drain, etc. Your boat's emergency shut-offs.",
      where: "Follow any hose downward and it ends at a seacock near the hull. Typical spots: engine bay (engine intake), under the toilet sink (toilet), under the galley sink.",
      look: "The handle should move a quarter-turn with firm hand force. Stiff = grease it. Stuck = have it serviced — a seacock you can't close is dangerous. Check for green corrosion on bronze.",
      when: "Exercise all of them a few times each season; grease at haul-out. Know where every single one is — count them." },
    { id: "shaftseal", name: "Shaft seal (stern gland)", icon: "💧",
      what: "The seal where the spinning propeller shaft exits the hull. On most Volvo shaft installations it's a black rubber lip seal that runs dry.",
      where: "In the bilge at the very back of the engine/gearbox — follow the shaft aft from the gearbox until it disappears through the hull.",
      look: "It should be dry. Dripping while running or at rest = it needs attention. After every launch, squeeze ('burp') the rubber boot until water squirts out, so it's water-lubricated, not air-locked.",
      when: "Burp at every launch. Replace roughly every 5 years / 500 h (workshop job, requires pulling the coupling)." },
    { id: "oilcheck", name: "Dipstick & coolant tank", icon: "🛢️",
      what: "Your two before-every-trip engine checks: lube oil level and closed-circuit coolant level.",
      where: "The dipstick is a bright (often yellow) loop handle on the side of the engine. The coolant expansion tank is a translucent tank with MIN/MAX marks, on or near the engine, with a pressure cap.",
      look: "Oil: between the two marks, and not milky (milky = water in oil, call a mechanic). Coolant: between MIN and MAX checked cold — never open the cap on a hot engine.",
      when: "Before every trip. Takes 60 seconds with the hatch open." },
    { id: "fuelsep", name: "Fuel filter / water separator", icon: "⛽",
      what: "A filter with a (often clear) bowl at the bottom that catches water and dirt in the diesel before it reaches the engine. Water in diesel is enemy #1.",
      where: "Mounted on a bulkhead in the engine bay, between tank and engine — look for a cartridge with a bowl and a small drain screw underneath.",
      look: "Water sits as a clearly visible layer at the bottom of the bowl (diesel floats on water). Any water = open the drain screw and let it out until clean diesel comes.",
      when: "Glance monthly; change the element yearly / 400 h. Keep the tank full over winter so it can't condensate." },
    { id: "belts", name: "Drive belt", icon: "➰",
      what: "The belt at the front of the engine that drives the alternator (charging!) and the circulation pump. Belt gone = no charging and an overheating engine.",
      where: "Front of the engine behind/under a guard. You'll see it wrap around several pulleys.",
      look: "Cracks across the ribs, glazed shiny sides, or black rubber dust on the engine below it = wearing out. Push midway between pulleys: ~1 cm of give.",
      when: "Check yearly and at any squealing sound. Carry a spare." },
    { id: "batteries", name: "Batteries & battery switches", icon: "🔋",
      what: "Typically one start battery (engine only) and a house bank (fridge, lights, instruments), plus possibly a thruster battery, kept apart so the house loads can never strand you.",
      where: "In boxes under the aft cabin berth or under the saloon floor (varies). The red battery switches are usually near the steps or in the engine bay.",
      look: "Terminals tight, no green/white fuzz, batteries strapped down. Rested voltage ~12.6 V+ = healthy; under 12.2 V = needs charging; chronically low = aging battery.",
      when: "Terminals yearly, voltage glance every trip, full charge before winter." },
    { id: "bilge", name: "Bilge & bilge pump", icon: "🕳️",
      what: "The lowest point inside the hull where any water collects, with an electric pump and a float switch that should fire automatically.",
      where: "Under the floorboards — usually a hatch in the saloon sole and in the engine bay. The float switch sits next to the pump.",
      look: "The bilge should be dry (a known boat is a dry boat — new water always has a story). Lift the float switch by hand: the pump must run.",
      when: "Glance every trip; test the float monthly. Find where the bilge water exits the hull so you recognise it pumping." },
    { id: "trimtabs", name: "Trim tabs", icon: "📐",
      what: "Two steel plates on the transom edge that press the stern up/bow down, used to get on the plane faster and to level the ride.",
      where: "Bottom edge of the transom, port and starboard, each with a hydraulic or electric ram.",
      look: "They should travel smoothly full range. Check the small anode on each tab and that hinge pins aren't loose.",
      when: "Function test at launch, anodes at haul-out." },
    { id: "thruster", name: "Bow thruster", icon: "↔️",
      what: "A propeller in a tunnel through the bow that pushes the bow sideways for docking — the Marex 370's best friend in a crosswind.",
      where: "The tunnel is visible at the bow below the waterline (haul-out) — inside, the motor sits under the forward berth/locker.",
      look: "At haul-out: prop free of weed and fishing line, small anode on the leg not eaten up. Inside: connections tight, no water in the compartment. Don't run it more than short bursts — it's not rated for continuous use.",
      when: "Anode and prop at every haul-out; quick function test at launch." },
    { id: "heater", name: "Diesel heater", icon: "🔥",
      what: "A Webasto/Eberspächer-type furnace that burns diesel from the main tank and blows warm air (or heats water) through the boat. Extends your season by months.",
      where: "Usually in a cockpit locker or the engine bay; you'll hear the fuel pump tick when it runs. The exhaust is a small skin fitting in the hull side.",
      look: "White smoke or burnt smell at start is normal for a few seconds; constant smoke, failure to start, or shutdowns = it's coking up and needs service.",
      when: "Run 20+ min at full power monthly (even in summer). Service when it misbehaves — typically every few hundred running hours." },
  ],
};

STRINGS.en = {
  app_title: "Marex 370",
  tab_home: "Home", tab_service: "Service", tab_lists: "Lists", tab_todos: "Todos", tab_guide: "Guide",
  title_service: "Service", title_lists: "Checklists", title_todos: "Todos", title_guide: "Know your boat", title_log: "Logbook",

  // home
  status: "Status", in_water: "🌊 In the water", on_land: "🛠️ On land",
  btn_haulout: "Haul out", btn_launch: "Launch",
  engine_hours: "Engine hours", not_set: "— not set —", updated_on: "updated {date}", btn_update: "Update",
  needs_attention: "Needs attention", service_link: "Service ›",
  nothing_due: "Nothing due.", all_good: "She's all shipshape ✨",
  unlogged_hint: "{n} items have no history yet — log them in Service.",
  quick_lists: "Quick checklists",
  chip_pretrip: "🧭 Before trip", chip_posttrip: "🏁 After trip", chip_monthly: "📅 Monthly",
  logbook: "Logbook", all_link: "All ›",
  add_note_btn: "＋ Note / photo", add_trip_btn: "＋ Log trip", add_fuel_btn: "＋ Fuel fill-up",
  start_here: "<strong>Start here 👋</strong> Set your current engine hours (read them off the dash display), then go through the Service tab and log roughly when each item was last done — a guess is fine. From then on the app tells you what's due.",
  install_hint: "<strong>📲 Make it an app:</strong> tap the Share button below, then <strong>Add to Home Screen</strong>. You get a real app icon, full screen, and it works offline at sea.",
  got_it: "Got it",

  // status
  st_ok: "OK", st_soon: "Due soon", st_overdue: "Overdue", st_unknown: "Not logged",
  d_overdue: "{n} days overdue", d_due: "due {date}", h_left: "{n} h left", h_overdue: "{n} h overdue",
  no_interval: "No interval tracked", log_first: "Log when this was last done to start tracking.",
  every: "Every", as_needed: "As needed", hr: "h", yr: "yr", mo: "mo",

  // service
  workshop: "workshop", last_lbl: "last",
  svc_footnote: "Intervals follow the Volvo Penta D-series schedule (whichever comes first: hours or calendar time). Adjust to your engine's manual if it differs.",
  add_service_btn: "＋ Add your own service item",
  baseline_notice: "Set your engine hours on the Home tab first — hour-based intervals can't be tracked without it.",
  expiry_card: "⏳ Expiry dates",
  expiry_hint: "Things with a printed expiry date: flares, fire extinguishers, lifejacket gas cartridges, first aid items, EPIRB battery. Add them here and they pop up on Home in good time.",
  add_expiry_btn: "＋ Add expiry date",
  expires_on: "expires {date}", expired_ago: "expired {n} days ago",

  // checklists
  of_lbl: "{a} of {b}", checked_lbl: "{a}/{b} checked", last_completed: "last completed {date}",
  log_completed_btn: "✓ Log as completed", check_all_btn: "Check all {n} items to complete",
  reset_boxes: "Reset checkboxes", reset_confirm: "Uncheck everything?",
  completed_alert: "Logged! ✓ The checklist has been reset for next time.",
  items_lbl: "{n} items", list_completed_log: "{name} completed",

  // todos
  todo_ph: "New todo… e.g. Buy spare impeller", add_btn: "Add",
  todo_head: "To do ({n})", done_head: "Done",
  todos_empty: "Nothing on the list. Add things the moment you spot them aboard — with a photo.",
  mark_done_btn: "✓ Mark as done", mark_undone_btn: "Mark as not done",
  delete_btn: "Delete", delete_todo_confirm: "Delete this todo?",
  todo_note_ph: "Details, measurements, part numbers…", added_lbl: "Added", done_lbl: "done",

  // guide
  guide_intro: "<strong>What am I looking at?</strong> Plain-language explanations of the parts you'll meet on your Marex 370. Open each one and snap a photo of <em>your</em> boat's version — next season you'll thank yourself.",
  yours: "📷 Yours",
  yours_tip: "Take a photo of this part on your boat so you always know what it looks like (and how it looked when healthy).",
  what_is: "What it is", where_find: "Where to find it", what_look: "What to look for", how_often: "How often",

  // logbook
  log_empty: "No entries yet.",
  fuel_card: "⛽ Fuel this year", fuel_total: "{l} L", fuel_cost: " · {p} kr",
  fuel_rate: "≈ {r} L/h average (from fills with hours)",

  // sheets / forms
  save: "Save", cancel: "Cancel", history: "History",
  date_lbl: "Date", hours_at_lbl: "Engine hours at the time", notes_lbl: "Notes", photos_lbl: "Photos",
  optional_ph: "optional",
  done_prefix: "Done: {name}", usually_workshop: "usually a workshop job",
  no_history_tip: "No history yet. If you're not sure when it was last done, log your best guess — or log it as done at the next service.",
  delete_item_btn: "Delete this item", delete_item_confirm: "Delete this service item and its history?",
  md_note_ph: "What was done, parts used, who did it…",

  hours_title: "Engine hours",
  hours_tip: "Read them off the engine display at the helm. Update after every trip — all hour-based service reminders build on this number.",
  current_hours_lbl: "Current hours", hours_eg_ph: "e.g. 412",
  invalid_number: "Enter a valid number.",
  lower_confirm: "That's lower than the current {n} h. Save anyway?",
  hours_updated: "Engine hours updated",

  note_title: "Logbook note",
  note_ph: "e.g. Odd vibration at 2500 rpm · checked prop, found rope",
  note_empty_alert: "Write something or add a photo.", photo_word: "Photo",

  trip_title: "Log trip", trip_where_lbl: "Trip / route", trip_where_ph: "e.g. Marina → Tunø and back",
  hours_after_lbl: "Engine hours after the trip", trip_word: "Trip",

  fuel_title: "Fuel fill-up", liters_lbl: "Litres filled", price_lbl: "Total price, kr (optional)",
  fuel_word: "Fuel", liters_invalid: "Enter the litres filled.",

  expiry_new_title: "Expiry date", name_lbl: "What", expiry_name_ph: "e.g. Flares (4 red hand flares)",
  expiry_date_lbl: "Expires", delete_expiry_confirm: "Delete this expiry date?",

  // custom service
  ns_title: "New service item", ns_name_ph: "e.g. Generator oil change",
  group_lbl: "Group", ns_hours_lbl: "Interval — engine hours (blank = none)",
  ns_months_lbl: "Interval — months (blank = none)", ns_why_lbl: "Notes", ns_why_ph: "Why / how",
  add_item_btn: "Add item", give_name: "Give it a name.",

  // settings
  settings: "Settings", boat_name_lbl: "Boat name", engine_lbl: "Engine", language_lbl: "Language / Sprog",
  backup_head: "Backup",
  backup_tip: "Data lives only on this phone. Export a backup now and then (photos are not included in the file — they stay on the device).",
  export_btn: "⬇️ Export backup", import_btn: "⬆️ Import backup",
  danger_head: "Danger zone", erase_btn: "Erase all data",
  erase_c1: "Erase ALL data? This cannot be undone.",
  erase_c2: "Really sure? Service history, todos and photos will be gone.",
  import_confirm: "Replace all current data with this backup?",
  import_failed: "Import failed: {e}", not_backup: "Not a valid backup file",
  storage_full: "Could not save data (storage full?). Export a backup from Settings.",

  // season
  season_water_log: "Launched — in the water 🌊", season_land_log: "Hauled out — on land 🛠️",
  launch_prompt: "She's in the water! Open the spring launch checklist?",
  haulout_prompt: "Hauled out. Open the haul-out & winterization checklist?",

  // photos
  viewer_delete: "Delete photo", viewer_close: "Close",
  delete_photo_confirm: "Delete this photo?", photo_failed: "Could not save the photo: {e}",
  add_photo_lbl: "Add",

  todo_done_log: "Todo done: {t}",
  delete_log_confirm: "Delete this log entry?", delete_entry_btn: "Delete entry",
};

ILLUS_STRINGS.en = {
  imp_vanes1: "rubber vanes — must be", imp_vanes2: "supple, none missing",
  imp_screws: "cover plate screws", imp_hub1: "brass hub (slides", imp_hub2: "onto pump shaft)",
  imp_title: "Raw water pump with the round cover removed — the impeller sits inside",

  str_lid: "lid — opens by hand", str_basket1: "basket: should look", str_basket2: "clear through the bowl",
  str_from1: "from seacock —", str_from2: "close before opening lid!", str_to: "to engine pump",
  str_title: "Sea strainer — seawater passes the basket before reaching the engine",

  ano_shaft: "shaft anode (collar)", ano_prop: "propeller", ano_rudder: "rudder", ano_disc: "rudder anode (disc)",
  ano_title: "Anodes corrode instead of your metal parts — replace at 50% gone",

  anf_hull: "hull / boot stripe", anf_wl: "waterline", anf_paint: "antifouling paint — everything below the waterline",
  anf_title: "A clean painted bottom = full speed and lower diesel burn",

  sea_handle1: "handle: ¼ turn,", sea_handle2: "firm but smooth",
  sea_hose1: "hose (double-clamped", sea_hose2: "below waterline)",
  sea_valve: "bronze ball valve", sea_thru: "through-hull fitting",
  sea_title: "One of these guards every hole in the hull — know where they all are",

  shs_gearbox: "gearbox", shs_seal1: "rubber seal — squeeze to", shs_seal2: "'burp' air out at launch",
  shs_shaft: "propeller shaft", shs_hull: "hull — sea outside",
  shs_title: "Where the shaft exits the hull. Should run dry — drips mean service time",

  oil_dip1: "dipstick (yellow loop):", oil_dip2: "oil between the marks, never milky",
  oil_cap1: "pressure cap — never", oil_cap2: "open when hot!", oil_cool: "coolant level, checked cold",
  oil_title: "The 60-second engine check before every trip",

  fue_elem: "filter element", fue_bowl1: "clear bowl: diesel...", fue_bowl2: "...water sinks below",
  fue_drain: "drain screw — let water out", fue_tank: "from tank",
  fue_title: "Water separator — check the bowl: any water layer gets drained out",

  bel_crank: "crank pulley", bel_alt: "alternator", bel_pump: "pump",
  bel_crack1: "look for cracks &amp;", bel_crack2: "black dust below",
  bel_title: "Press midway between pulleys — about 1 cm of give is right",

  bat_term1: "+ terminal: tight,", bat_term2: "no green fuzz",
  bat_house1: "house bank: fridge,", bat_house2: "lights, instruments",
  bat_volt: "rested 12.6 V+ = healthy · below 12.2 V = charge it",
  bat_start: "START", bat_house: "HOUSE",
  bat_title: "Separate banks so the fridge can never strand you",

  bil_pump: "bilge pump", bil_float1: "float switch — lift it", bil_float2: "by hand: pump must run",
  bil_out: "out through hull side", bil_low: "lowest point of the hull — should be DRY",
  bil_title: "New water in the bilge always has a story — find it",

  tri_ram: "hydraulic ram", tri_plate: "steel plate, hinged", tri_anode: "small anode on each tab",
  tri_title: "Transom seen from behind — tabs press the stern up to level the ride",

  thr_tunnel: "tunnel through the bow", thr_prop: "prop + small anode — keep free of weed &amp; line",
  thr_wl: "waterline",
  thr_title: "Bow seen from the side — the thruster pushes the bow sideways",

  hea_burn1: "burner — diesel from", hea_burn2: "the main tank",
  hea_duct: "warm air ducts to cabins", hea_exh: "exhaust through hull side",
  hea_pump: "fuel pump (ticks when running)",
  hea_title: "Run it hard 20 min a month so it never cokes up",

  rud_bear1: "rudder bearing &amp; tiller arm", rud_bear2: "(inside the boat)",
  rud_stock1: "rudder stock — grab the", rud_stock2: "blade &amp; feel for play", rud_blade: "rudder blade",
  rud_title: "At haul-out: push the rudder by hand — clunky play = worn bearing",
};
