/* Seed content for the Marex 370 maintenance app.
   Intervals follow the Volvo Penta D4/D6 operator's manual rhythm
   (oil/filter 200 h or 12 months, impeller 12 months, coolant 4 years, etc.)
   plus standard BoatUS-style commissioning / winterization practice. */

const SERVICE_GROUPS = [
  { id: "engine",    name: "Engine",             icon: "⚙️" },
  { id: "underwater",name: "Underwater & drive", icon: "🌊" },
  { id: "systems",   name: "Boat systems",       icon: "🔌" },
  { id: "safety",    name: "Safety gear",        icon: "🦺" },
];

/* intervalHours / intervalMonths: whichever comes first.
   pro: true = most owners leave this to a workshop. */
const SERVICES = [
  // ENGINE — Volvo Penta D4/D6
  { id: "oil",        group: "engine", name: "Engine oil & filter",
    intervalHours: 200, intervalMonths: 12,
    why: "Fresh oil is the cheapest engine insurance there is. Old oil turns acidic and wears the engine from the inside. Change while the engine is warm so the old oil drains fully." },
  { id: "fuelfilter", group: "engine", name: "Fuel filters (engine + water separator)",
    intervalHours: 400, intervalMonths: 12,
    why: "Diesel attracts water and grows bacteria ('diesel bug'). The filters and the water-separator bowl are what stand between that and your injectors. Drain the separator bowl whenever you see water in it." },
  { id: "impeller",   group: "engine", name: "Raw water impeller",
    intervalMonths: 12,
    why: "A small rubber paddle wheel that pumps seawater through the engine cooling system. When it fails the engine overheats within minutes. Cheap part, big consequences — replace every season and keep a spare aboard." },
  { id: "belts",      group: "engine", name: "Drive belts — inspect & tension",
    intervalMonths: 12,
    why: "Belts drive the alternator and circulation pump. Look for cracks, glazing and black rubber dust below the belt (a wear sign). Press midway between pulleys: about 1 cm of give is right." },
  { id: "airfilter",  group: "engine", name: "Air filter",
    intervalHours: 400, intervalMonths: 24,
    why: "A clogged filter makes the engine smoke and lose power. Quick visual check yearly, replace when dirty." },
  { id: "coolant",    group: "engine", name: "Coolant (VCS) replace",
    intervalMonths: 48, pro: true,
    why: "The closed-circuit coolant (Volvo's yellow VCS) loses its corrosion protection over time. Check the level at every trip; replace the fluid every 4 years." },
  { id: "valves",     group: "engine", name: "Valve clearance check",
    intervalHours: 1000, intervalMonths: 60, pro: true,
    why: "A workshop job on the Volvo schedule. Worth booking together with a big service." },
  { id: "heatex",     group: "engine", name: "Heat exchanger & aftercooler service",
    intervalHours: 1000, intervalMonths: 48, pro: true,
    why: "Seawater slowly scales up the cooling cores. A workshop cleans and pressure-tests them. Skipping this is a classic cause of creeping overheating on older D-series engines." },

  // UNDERWATER & DRIVE
  { id: "anodes",     group: "underwater", name: "Sacrificial anodes",
    intervalMonths: 12,
    why: "Zinc/aluminium lumps on the shaft, rudder, trim tabs and thruster that corrode so your metal parts don't. Replace any that are more than half eaten — they are cheap insurance. Never paint over them." },
  { id: "antifoul",   group: "underwater", name: "Antifouling paint",
    intervalMonths: 12,
    why: "Keeps barnacles and weed off the hull. A fouled hull can cost you several knots and a lot of diesel. Repaint (or at least touch up) every spring before launch." },
  { id: "propshaft",  group: "underwater", name: "Propeller & shaft inspection",
    intervalMonths: 12,
    why: "Check the prop for dings (they cause vibration), and look for fishing line wrapped at the shaft seal — it destroys seals. Grab the shaft and feel for play in the cutless bearing." },
  { id: "shaftseal",  group: "underwater", name: "Shaft seal / stern gland",
    intervalHours: 500, intervalMonths: 60, pro: true,
    why: "Where the propeller shaft exits the hull. The Volvo rubber seal must be 'burped' (squeezed to release air) every launch, and replaced roughly every 5 years. It should run dry — water here goes straight in the bilge." },
  { id: "seacocks",   group: "underwater", name: "Seacocks — exercise & grease",
    intervalMonths: 12,
    why: "Every valve on a hole in the hull. Open and close each one fully a few times so they never seize — a seacock you can't close in an emergency is a sinking risk. Grease at haul-out." },
  { id: "hoses",      group: "underwater", name: "Hoses & clamps below waterline",
    intervalMonths: 12,
    why: "Squeeze hoses (soft or cracked = replace) and check every clamp is tight and not rusty. Critical hoses below the waterline should be double-clamped." },
  { id: "thruster",   group: "underwater", name: "Bow thruster — anode, prop & oil",
    intervalMonths: 12,
    why: "The thruster leg has its own small anode that vanishes fast. Check the propeller spins free of weed and line, and check gear oil if your model allows." },
  { id: "rudder",     group: "underwater", name: "Rudder & steering check",
    intervalMonths: 12,
    why: "At haul-out: push the rudder by hand — noticeable play means worn bearings. Turn the wheel lock-to-lock and check hydraulic fluid level at the helm pump." },

  // BOAT SYSTEMS
  { id: "batteries",  group: "systems", name: "Batteries — terminals & condition",
    intervalMonths: 12,
    why: "Clean and grease terminals, check they're strapped tight, and verify a rested voltage of ~12.6 V+. Most Marex boats have a separate start battery and house bank — check both." },
  { id: "freshwater", group: "systems", name: "Freshwater system flush & sanitize",
    intervalMonths: 12,
    why: "After winter, flush out the antifreeze and sanitize the tank (e.g. with a chlorine solution), then rinse. Also check the pump doesn't cycle when no tap is open — that means a leak." },
  { id: "toilet",     group: "systems", name: "Toilet & holding tank service",
    intervalMonths: 12,
    why: "Lubricate the pump/valves, check the joker valve, rinse the holding tank. Treat hoses with respect — old sanitation hose is the usual source of smells." },
  { id: "heater",     group: "systems", name: "Diesel heater (Webasto/Eberspächer) service",
    intervalMonths: 12, pro: true,
    why: "Common in Marex boats. Run it at full power 20+ minutes monthly even in summer so it doesn't coke up; have it serviced when it starts smoking or smelling." },
  { id: "gas",        group: "systems", name: "Gas system leak test",
    intervalMonths: 12, pro: true,
    why: "If you have a gas stove: hoses have a printed expiry date, and the system should be leak-tested (a professional check every couple of years is money well spent). Gas sinks into the bilge — treat it seriously." },
  { id: "windlass",   group: "systems", name: "Anchor windlass & chain",
    intervalMonths: 12,
    why: "Grease the windlass, run the chain out and inspect it, and re-mark the length markings. Check the chain-to-anchor shackle is seized with wire." },
  { id: "trimtabs",   group: "systems", name: "Trim tabs check",
    intervalMonths: 12,
    why: "Run them full up/down and watch them move. Check hydraulic lines, hinge pins, and the small anodes on the tabs themselves." },
  { id: "canvas",     group: "systems", name: "Canvas, hatches & seal lubrication",
    intervalMonths: 12,
    why: "Silicone-grease the rubber seals on hatches and the sliding roof, treat zippers, and check drains in the cockpit aren't blocked." },

  // SAFETY
  { id: "extinguisher", group: "safety", name: "Fire extinguishers check",
    intervalMonths: 12,
    why: "Gauge in the green, pin sealed, no corrosion. Turn powder extinguishers upside down and shake so the powder doesn't cake. Professional service per the label." },
  { id: "lifejackets", group: "safety", name: "Lifejackets — inspect & service",
    intervalMonths: 12,
    why: "For inflatables: check the gas cylinder is screwed tight and not corroded, and the auto-cartridge is in date. Most makers want a full service every 1–2 years." },
  { id: "flares",     group: "safety", name: "Flares & signals expiry",
    intervalMonths: 12,
    why: "Flares expire after 3–4 years. Check dates each spring and replace expired ones (hand them in — don't bin them)." },
  { id: "firstaid",   group: "safety", name: "First aid kit restock",
    intervalMonths: 12,
    why: "Check expiry on everything, restock plasters and seasickness tablets before the season." },
  { id: "alarms",     group: "safety", name: "Smoke / gas / CO alarms",
    intervalMonths: 12,
    why: "Press-test the alarms and change batteries every spring. A diesel heater plus a closed boat makes a CO alarm cheap life insurance." },
];

/* Checklists. itemtext + optional sub explanation. */
const CHECKLISTS = [
  {
    id: "launch", name: "Spring — onto the water", icon: "🌱",
    desc: "Launch & commissioning. Work top-down: everything on land first, then the in-water checks the moment she floats.",
    sections: [
      { name: "On land, before launch", items: [
        { id: "af",      text: "Antifouling painted / touched up", sub: "Hull clean, sanded where flaking, fresh coat applied. Don't paint the anodes!" },
        { id: "anodes",  text: "Anodes checked — replaced if >50% gone", sub: "Shaft, rudder, trim tabs, bow thruster." },
        { id: "hull",    text: "Hull, prop, shaft & rudder inspected", sub: "Dings in prop, play in shaft/rudder, damage or blisters in gelcoat." },
        { id: "seacock", text: "All seacocks exercised & greased", sub: "Open/close each fully a few times. They must move freely." },
        { id: "hoses",   text: "Hoses & clamps below waterline checked", sub: "Squeeze test, tighten clamps, double clamps on critical hoses." },
        { id: "impeller",text: "Impeller fitted & raw water system reconnected", sub: "If you removed it for winter. Light dish soap on the blades helps the dry start." },
        { id: "engine",  text: "Engine: oil level, coolant level, belts", sub: "Oil between marks, coolant between MIN/MAX (cold), belts firm without cracks." },
        { id: "batt",    text: "Batteries connected & fully charged", sub: "Terminals tight and greased. Check voltage ~12.6 V+ rested." },
        { id: "plugs",   text: "DRAIN PLUGS IN", sub: "The classic. Check every drain plug is fitted before she touches water." },
      ]},
      { name: "In the water — first 10 minutes", items: [
        { id: "leaks",   text: "Leak check at shaft seal, seacocks & through-hulls", sub: "Go below immediately and look. A dry bilge should stay dry." },
        { id: "burp",    text: "Shaft seal burped (Volvo rubber seal)", sub: "Squeeze the rubber boot until water spurts out — this releases trapped air so it self-lubricates." },
        { id: "start",   text: "Engine started — raw water out of exhaust within seconds", sub: "No water = stop immediately. Check seacock open and strainer primed." },
        { id: "gauges",  text: "Oil pressure, temperature & charging normal", sub: "Watch the gauges for the first few minutes at the dock." },
        { id: "steer",   text: "Steering lock-to-lock, throttle & gear tested", sub: "Forward/reverse briefly against the lines." },
        { id: "thruster",text: "Bow thruster & trim tabs tested", sub: "" },
      ]},
      { name: "Commissioning the boat", items: [
        { id: "water",   text: "Freshwater system flushed & refilled", sub: "Flush all antifreeze out of every tap (hot + cold) before filling for use." },
        { id: "elec",    text: "Nav lights, horn, wipers, VHF tested", sub: "" },
        { id: "bilge",   text: "Bilge pump tested — auto float & manual", sub: "Lift the float switch by hand and listen for the pump." },
        { id: "safety",  text: "Safety gear aboard & in date", sub: "Lifejackets, extinguishers, flares, first aid kit." },
        { id: "lines",   text: "Mooring lines, fenders & anchor rigged", sub: "" },
        { id: "hours",   text: "Engine hours logged as season start", sub: "Update the hours on the Home tab." },
      ]},
    ],
  },
  {
    id: "haulout", name: "Autumn — up from the water", icon: "❄️",
    desc: "Haul-out & winterization. The golden rule: no water anywhere it can freeze, no half-empty diesel tank, no flat batteries.",
    sections: [
      { name: "In the water, before haul-out", items: [
        { id: "fuel",    text: "Diesel tank filled + biocide added", sub: "A full tank can't condensate water on the walls. Add a diesel bug treatment." },
        { id: "oil",     text: "Engine oil & filter changed (warm engine)", sub: "Old acidic oil should not sit in the engine all winter. Run her warm first." },
        { id: "holding", text: "Holding tank pumped out & rinsed", sub: "" },
      ]},
      { name: "At haul-out", items: [
        { id: "wash",    text: "Hull pressure-washed immediately", sub: "Growth comes off 10× easier while still wet." },
        { id: "inspect", text: "Hull, prop, shaft, rudder & anodes inspected", sub: "Photograph anything suspicious now — easy to forget by spring. Note anode condition." },
      ]},
      { name: "On land — engine & systems", items: [
        { id: "raw",     text: "Raw water system winterized", sub: "Close seacock, open strainer, run engine on antifreeze poured into the strainer until it runs coloured out of the exhaust." },
        { id: "imp",     text: "Impeller removed (or noted as left in)", sub: "Stored flat it keeps its shape. Write down what you did so spring-you knows." },
        { id: "fresh",   text: "Freshwater system drained + antifreeze", sub: "Tank, pump, water heater, all taps (hot & cold), deck shower. Non-toxic propylene glycol only." },
        { id: "toilet",  text: "Toilet & holding tank winterized", sub: "Pump antifreeze through the toilet and leave some in the bowl & tank." },
        { id: "batt",    text: "Batteries fully charged + disconnected or on maintainer", sub: "A charged battery doesn't freeze; a flat one can crack at -10 °C." },
        { id: "coolant", text: "Coolant antifreeze strength checked", sub: "The closed circuit should protect to at least -25 °C." },
      ]},
      { name: "On land — boat", items: [
        { id: "remove",  text: "Electronics, lifejackets, cushions, food & liquids removed", sub: "Anything that can freeze, mold or get stolen goes home." },
        { id: "fridge",  text: "Fridge defrosted & propped open", sub: "" },
        { id: "vent",    text: "Boat ventilated + moisture absorbers placed", sub: "Open lockers and floor hatches so air circulates." },
        { id: "grease",  text: "Seacocks greased, left as the yard advises", sub: "" },
        { id: "cover",   text: "Cover fitted & checked for chafe", sub: "Check it again after the first storm." },
        { id: "hours",   text: "Engine hours logged as season end", sub: "Update the hours on the Home tab." },
      ]},
    ],
  },
  {
    id: "pretrip", name: "Before every trip", icon: "🧭",
    desc: "The 5-minute check before you cast off. Resets itself automatically so it's ready every time.",
    autoReset: true,
    sections: [
      { name: "Engine bay (open the hatch!)", items: [
        { id: "oil",    text: "Oil level between the marks", sub: "" },
        { id: "coolant",text: "Coolant between MIN/MAX", sub: "Only check cold." },
        { id: "look",   text: "Look & sniff: no fuel, oil or water where it shouldn't be", sub: "30 seconds with eyes and nose finds most problems early." },
        { id: "strainer",text:"Sea strainer clear", sub: "Glance through the clear bowl — no weed or plastic bags." },
      ]},
      { name: "Boat", items: [
        { id: "bilge",  text: "Bilge dry, pump on auto", sub: "" },
        { id: "fuel",   text: "Enough diesel: ⅓ out, ⅓ home, ⅓ reserve", sub: "" },
        { id: "batt",   text: "Battery switches on, voltage OK", sub: "" },
        { id: "weather",text: "Weather & wind forecast checked", sub: "" },
        { id: "plan",   text: "Told someone where you're going", sub: "" },
        { id: "jackets",text: "Lifejackets out — everyone aboard has one", sub: "" },
      ]},
      { name: "After engine start", items: [
        { id: "water",  text: "Raw water flowing from exhaust", sub: "Look over the side within seconds of starting." },
        { id: "gauges", text: "Oil pressure & charging normal", sub: "" },
        { id: "lines",  text: "Fenders in, no lines trailing in the water", sub: "A line in the prop ends the trip." },
      ]},
    ],
  },
  {
    id: "posttrip", name: "After every trip", icon: "🏁",
    desc: "Leave the boat so the next trip starts easy. Resets automatically.",
    autoReset: true,
    sections: [
      { name: "Securing the boat", items: [
        { id: "hours",  text: "Engine hours updated in the app", sub: "Home tab → update hours. This drives all the service reminders." },
        { id: "lines",  text: "Mooring lines & fenders set for coming weather", sub: "" },
        { id: "bilge",  text: "Bilge checked dry", sub: "" },
        { id: "seacocks",text:"Toilet & galley seacocks closed if leaving the boat", sub: "" },
        { id: "shore",  text: "Shore power connected, charger on", sub: "" },
        { id: "fridge", text: "Perishables out of the fridge (if away >2 days)", sub: "" },
        { id: "rinse",  text: "Quick freshwater rinse of cockpit & stainless", sub: "Salt is what ages the boat." },
        { id: "canvas", text: "Canvas/covers on, hatches closed, boat locked", sub: "" },
      ]},
    ],
  },
  {
    id: "monthly", name: "Monthly in season", icon: "📅",
    desc: "A 30-minute round once a month keeps surprises away. Resets automatically when you complete it.",
    autoReset: true,
    sections: [
      { name: "The monthly round", items: [
        { id: "strainer",text:"Sea strainer opened & cleaned", sub: "Close the seacock first, clean the basket, reopen — then check water flows when the engine starts." },
        { id: "belts",  text: "Belt glance: tension OK, no black dust", sub: "" },
        { id: "clamps", text: "Engine bay hose clamps eyeballed", sub: "" },
        { id: "batt",   text: "Battery terminals & charger state checked", sub: "" },
        { id: "bilgep", text: "Bilge pump float switch tested by hand", sub: "" },
        { id: "anode",  text: "Visible anodes checked (trim tabs / thruster if reachable)", sub: "" },
        { id: "chafe",  text: "Mooring lines checked for chafe", sub: "" },
        { id: "ext",    text: "Fire extinguisher gauges in the green", sub: "" },
        { id: "heater", text: "Diesel heater run 20 min at full power", sub: "Keeps it from coking up." },
        { id: "wash",   text: "Boat washed, drains & scuppers clear", sub: "" },
      ]},
    ],
  },
];

/* "What am I looking at" guide. Each entry gets an SVG illustration by id. */
const GUIDE = [
  { id: "impeller", name: "Raw water impeller", icon: "🌀",
    what: "A star-shaped rubber wheel inside a bronze pump on the front/side of the engine. It sucks seawater in through the hull and pushes it through the heat exchanger to cool the engine.",
    where: "On the Volvo Penta D-series it sits behind a round cover plate with 4–6 screws on the raw water pump, low at the front of the engine. Follow the hose from the sea strainer — it ends at the pump.",
    look: "Rubber blades should be supple and unbroken. Cracked, stiff or missing blades = replace now (and find the missing bits in the heat exchanger before they block it).",
    when: "Replace every 12 months. Always keep a spare impeller kit aboard." },
  { id: "strainer", name: "Sea strainer", icon: "🧺",
    what: "A filter with a clear bowl that catches weed, plastic and jellyfish before they reach the engine's cooling water pump.",
    where: "Between the engine's raw water seacock and the engine, in the engine bay — usually mounted on a bulkhead near the engine, with a transparent lid or bowl.",
    look: "You should be able to see through it. Weed, mud or a collapsed basket means cleaning time. Close the seacock before opening it!",
    when: "Glance before every trip, clean monthly in season." },
  { id: "anodes", name: "Sacrificial anodes", icon: "🧲",
    what: "Blocks of zinc (salt water) or aluminium that corrode away on purpose, protecting your propeller, shaft, rudder and trim tabs from galvanic corrosion.",
    where: "On the shaft (a collar), on the rudder, on each trim tab, and a small ring or disc on the bow thruster leg. There may also be a pear-shaped hull anode.",
    look: "A healthy anode is rough and matte from corroding. Shiny untouched anodes might not have good contact. More than ~50% eaten = replace.",
    when: "Check at every haul-out, replace yearly or at 50% gone. Never paint them." },
  { id: "antifoul", name: "Antifouling", icon: "🎨",
    what: "Biocide paint on the hull bottom that stops barnacles and weed from growing. A fouled hull steals speed and burns extra diesel.",
    where: "Everything below the waterline. The prop and shaft can get their own special prop coating.",
    look: "At haul-out: if the bottom was slimy/green but rinses clean, the paint is working. Barnacles stuck on = time for a fresh coat (or a better paint).",
    when: "Repaint each spring before launch. Check local rules — some Baltic harbours restrict paint types." },
  { id: "seacocks", name: "Seacocks & through-hulls", icon: "🔩",
    what: "Ball valves on every hole in the hull: engine cooling intake, toilet in/out, galley drain, etc. Your boat's emergency shut-offs.",
    where: "Follow any hose downward and it ends at a seacock near the hull. Typical spots: engine bay (engine intake), under the toilet sink (toilet), under the galley sink.",
    look: "The handle should move a quarter-turn with firm hand force. Stiff = grease it. Stuck = have it serviced — a seacock you can't close is dangerous. Check for green corrosion on bronze.",
    when: "Exercise all of them a few times each season; grease at haul-out. Know where every single one is — count them." },
  { id: "shaftseal", name: "Shaft seal (stern gland)", icon: "💧",
    what: "The seal where the spinning propeller shaft exits the hull. On most Volvo shaft installations it's a black rubber lip seal that runs dry.",
    where: "In the bilge at the very back of the engine/gearbox — follow the shaft aft from the gearbox until it disappears through the hull.",
    look: "It should be dry. Dripping while running or at rest = it needs attention. After every launch, squeeze ('burp') the rubber boot until water squirts out, so it's water-lubricated, not air-locked.",
    when: "Burp at every launch. Replace roughly every 5 years / 500 h (workshop job, requires pulling the coupling)." },
  { id: "oilcheck", name: "Dipstick & coolant tank", icon: "🛢️",
    what: "Your two before-every-trip engine checks: lube oil level and closed-circuit coolant level.",
    where: "The dipstick is a bright (often yellow) loop handle on the side of the engine. The coolant expansion tank is a translucent tank with MIN/MAX marks, on or near the engine, with a pressure cap.",
    look: "Oil: between the two marks, and not milky (milky = water in oil, call a mechanic). Coolant: between MIN and MAX checked cold — never open the cap on a hot engine.",
    when: "Before every trip. Takes 60 seconds with the hatch open." },
  { id: "fuelsep", name: "Fuel filter / water separator", icon: "⛽",
    what: "A filter with a (often clear) bowl at the bottom that catches water and dirt in the diesel before it reaches the engine. Water in diesel is enemy #1.",
    where: "Mounted on a bulkhead in the engine bay, between tank and engine — look for a cartridge with a bowl and a small drain screw underneath.",
    look: "Water sits as a clearly visible layer at the bottom of the bowl (diesel floats on water). Any water = open the drain screw and let it out until clean diesel comes.",
    when: "Glance monthly; change the element yearly / 400 h. Keep the tank full over winter so it can't condensate." },
  { id: "belts", name: "Drive belt", icon: "➰",
    what: "The belt at the front of the engine that drives the alternator (charging!) and the circulation pump. Belt gone = no charging and an overheating engine.",
    where: "Front of the engine behind/under a guard. You'll see it wrap around several pulleys.",
    look: "Cracks across the ribs, glazed shiny sides, or black rubber dust on the engine below it = wearing out. Push midway between pulleys: ~1 cm of give.",
    when: "Check yearly and at any squealing sound. Carry a spare." },
  { id: "batteries", name: "Batteries & battery switches", icon: "🔋",
    what: "Typically one start battery (engine only) and a house bank (fridge, lights, instruments), plus possibly a thruster battery, kept apart so the house loads can never strand you.",
    where: "In boxes under the aft cabin berth or under the saloon floor (varies). The red battery switches are usually near the steps or in the engine bay.",
    look: "Terminals tight, no green/white fuzz, batteries strapped down. Rested voltage ~12.6 V+ = healthy; under 12.2 V = needs charging; chronically low = aging battery.",
    when: "Terminals yearly, voltage glance every trip, full charge before winter." },
  { id: "bilge", name: "Bilge & bilge pump", icon: "🕳️",
    what: "The lowest point inside the hull where any water collects, with an electric pump and a float switch that should fire automatically.",
    where: "Under the floorboards — usually a hatch in the saloon sole and in the engine bay. The float switch sits next to the pump.",
    look: "The bilge should be dry (a known boat is a dry boat — new water always has a story). Lift the float switch by hand: the pump must run.",
    when: "Glance every trip; test the float monthly. Find where the bilge water exits the hull so you recognise it pumping." },
  { id: "trimtabs", name: "Trim tabs", icon: "📐",
    what: "Two steel plates on the transom edge that press the stern up/bow down, used to get on the plane faster and to level the ride.",
    where: "Bottom edge of the transom, port and starboard, each with a hydraulic or electric ram.",
    look: "They should travel smoothly full range. Check the small anode on each tab and that hinge pins aren't loose.",
    when: "Function test at launch, anodes at haul-out." },
  { id: "thruster", name: "Bow thruster", icon: "↔️",
    what: "A propeller in a tunnel through the bow that pushes the bow sideways for docking — the Marex 370's best friend in a crosswind.",
    where: "The tunnel is visible at the bow below the waterline (haul-out) — inside, the motor sits under the forward berth/locker.",
    look: "At haul-out: prop free of weed and fishing line, small anode on the leg not eaten up. Inside: connections tight, no water in the compartment. Don't run it more than short bursts — it's not rated for continuous use.",
    when: "Anode and prop at every haul-out; quick function test at launch." },
  { id: "heater", name: "Diesel heater", icon: "🔥",
    what: "A Webasto/Eberspächer-type furnace that burns diesel from the main tank and blows warm air (or heats water) through the boat. Extends your season by months.",
    where: "Usually in a cockpit locker or the engine bay; you'll hear the fuel pump tick when it runs. The exhaust is a small skin fitting in the hull side.",
    look: "White smoke or burnt smell at start is normal for a few seconds; constant smoke, failure to start, or shutdowns = it's coking up and needs service.",
    when: "Run 20+ min at full power monthly (even in summer). Service when it misbehaves — typically every few hundred running hours." },
];
